import { NextRequest, NextResponse } from 'next/server';
import { requireUserId } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { uploadBuffer } from '@/lib/s3';

export const dynamic = 'force-dynamic';

// POST /api/entities/[id]/filing-receipt — Save a filing receipt as a document
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const userId = await requireUserId();
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { id: entityId } = await params;
    const body = await req.json();
    const { filingType, reference, status, description, submittedAt, formData, companyName, companyNumber } = body;

    if (!reference) {
      return NextResponse.json({ error: 'Filing reference is required' }, { status: 400 });
    }

    // Generate receipt text
    const newAddress = formData
      ? [formData.premises, formData.addressLine1, formData.addressLine2, formData.city, formData.region, formData.postcode, formData.country].filter(Boolean).join(', ')
      : '';

    const receiptLines = [
      '═══════════════════════════════════════════════════════',
      '         COMPANIES HOUSE FILING RECEIPT',
      '               HomeLedger System',
      '═══════════════════════════════════════════════════════',
      '',
      `Company:        ${companyName || 'N/A'}`,
      `Company Number: ${companyNumber || 'N/A'}`,
      '',
      '───────────────────────────────────────────────────────',
      '  FILING DETAILS',
      '───────────────────────────────────────────────────────',
      '',
      `Filing Type:    ${filingType || 'N/A'}`,
      `Description:    ${description || 'N/A'}`,
      `Reference:      ${reference}`,
      `Status:         ${status || 'N/A'}`,
      `Submitted:      ${submittedAt ? new Date(submittedAt).toLocaleString('en-GB', { dateStyle: 'full', timeStyle: 'medium' }) : 'N/A'}`,
      '',
    ];

    if (newAddress) {
      receiptLines.push(
        '───────────────────────────────────────────────────────',
        '  NEW ADDRESS SUBMITTED',
        '───────────────────────────────────────────────────────',
        '',
        `  ${newAddress}`,
        '',
      );
    }

    receiptLines.push(
      '───────────────────────────────────────────────────────',
      '  WHAT HAPPENS NEXT',
      '───────────────────────────────────────────────────────',
      '',
      '  • Companies House processes the change immediately',
      '  • You will receive a confirmation email from CH',
      '  • The public register is updated within minutes',
      '  • A confirmation letter is sent to the new address',
      '',
      '═══════════════════════════════════════════════════════',
      `  Generated by HomeLedger on ${new Date().toLocaleString('en-GB')}`,
      '═══════════════════════════════════════════════════════',
    );

    const receiptText = receiptLines.join('\n');
    const fileName = `CH-Filing-Receipt-${reference.replace(/\s+/g, '-')}.txt`;

    // Upload to S3
    const cloudStoragePath = await uploadBuffer(
      Buffer.from(receiptText, 'utf-8'),
      fileName,
      'text/plain',
      false
    );

    // Create ScannedDocument record
    const doc = await prisma.scannedDocument.create({
      data: {
        userId,
        entityId,
        cloudStoragePath,
        isPublic: false,
        fileName,
        senderName: 'Companies House',
        documentType: 'other',
        summary: `Filing receipt for ${description || filingType}. Reference: ${reference}. Status: ${status}.`,
        actionRequired: false,
        referenceNumber: reference,
        status: 'processed',
        confidenceScore: 1.0,
        tags: ['companies-house', 'filing-receipt', filingType].filter(Boolean),
        notes: `Auto-generated receipt from HomeLedger filing submission.\n${newAddress ? `New address: ${newAddress}` : ''}`,
        processedAt: new Date(),
      },
    });

    return NextResponse.json({ success: true, documentId: doc.id, fileName });
  } catch (error) {
    console.error('Error saving filing receipt:', error);
    return NextResponse.json({ error: 'Failed to save receipt' }, { status: 500 });
  }
}
