/**
 * Level 3 ETHC — Ethics for Accountants (32 questions)
 * Run: npx tsx prisma/seed-questions-l3-ethc.ts
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
interface QS { questionText: string; topic: string; difficulty: 'easy'|'medium'|'hard'; syllabusRef: string; aiExplanation: string; options: { text: string; correct: boolean; explanation: string }[]; }
async function seedModule(code: string, questions: QS[]) {
  const mod = await (prisma as any).examModule.findFirst({ where: { code } });
  if (!mod) { console.log(`  ⚠️ ${code} not found`); return; }
  const existing = await (prisma as any).question.count({ where: { moduleId: mod.id } });
  let added = 0;
  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const dup = await (prisma as any).question.findFirst({ where: { moduleId: mod.id, questionText: q.questionText } });
    if (dup) continue;
    const created = await (prisma as any).question.create({
      data: { moduleId: mod.id, questionText: q.questionText, topic: q.topic, difficulty: q.difficulty, syllabusRef: q.syllabusRef, aiExplanation: q.aiExplanation, sortOrder: existing + i + 1 },
    });
    for (let j = 0; j < q.options.length; j++) {
      await (prisma as any).questionOption.create({
        data: { questionId: created.id, optionText: q.options[j].text, isCorrect: q.options[j].correct, explanation: q.options[j].explanation, sortOrder: j + 1 },
      });
    }
    added++;
  }
  console.log(`  ✅ ${code}: ${added} new (${existing} existed)`);
}

const ETHC: QS[] = [
  // --- 5 Fundamental Principles (10) ---
  { questionText: 'Which of these is NOT one of the five fundamental principles of the AAT Code of Professional Ethics?', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.1',
    aiExplanation: 'The five principles are: Integrity, Objectivity, Professional Competence and Due Care, Confidentiality, Professional Behaviour. Profitability is not a principle.',
    options: [{ text: 'Integrity', correct: false, explanation: 'IS a fundamental principle.' },{ text: 'Objectivity', correct: false, explanation: 'IS a fundamental principle.' },{ text: 'Profitability', correct: true, explanation: 'Correct! Not a principle.' },{ text: 'Confidentiality', correct: false, explanation: 'IS a fundamental principle.' }] },
  { questionText: 'The principle of integrity means:', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.2',
    aiExplanation: 'Integrity requires being straightforward and honest in all professional and business relationships. It implies fair dealing and truthfulness. An accountant must not be associated with misleading information.',
    options: [{ text: 'Being straightforward and honest', correct: true, explanation: 'Correct!' },{ text: 'Keeping client information secret', correct: false, explanation: 'That is confidentiality.' },{ text: 'Maintaining up-to-date knowledge', correct: false, explanation: 'That is professional competence.' },{ text: 'Not bringing the profession into disrepute', correct: false, explanation: 'That is professional behaviour.' }] },
  { questionText: 'Objectivity requires an accountant to:', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.3',
    aiExplanation: 'Objectivity means not allowing bias, conflict of interest, or undue influence to override professional or business judgements. The accountant must be impartial and independent in their work.',
    options: [{ text: 'Not allow bias or conflicts of interest to influence judgement', correct: true, explanation: 'Correct!' },{ text: 'Always agree with the client', correct: false, explanation: 'Objectivity may require disagreeing.' },{ text: 'Maximise the client\'s profit', correct: false, explanation: 'Not the role of objectivity.' },{ text: 'Keep all information confidential', correct: false, explanation: 'That is confidentiality.' }] },
  { questionText: 'Professional competence and due care requires:', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.4',
    aiExplanation: 'This principle has two aspects: (1) Attaining and maintaining professional knowledge and skill (CPD), (2) Acting diligently and in accordance with applicable standards. The accountant must not accept work they are not competent to perform.',
    options: [{ text: 'Maintaining knowledge and acting diligently', correct: true, explanation: 'Correct!' },{ text: 'Charging the highest possible fees', correct: false, explanation: 'Not related to competence.' },{ text: 'Refusing all complex work', correct: false, explanation: 'Should develop skills, not avoid challenges.' },{ text: 'Delegating all work to juniors', correct: false, explanation: 'Must ensure quality regardless of delegation.' }] },
  { questionText: 'Confidentiality means an accountant must:', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.5',
    aiExplanation: 'Confidentiality: not disclose information acquired through professional relationships without proper authority, and not use such information for personal advantage. Continues even after the relationship ends.',
    options: [{ text: 'Not disclose client information without authority', correct: true, explanation: 'Correct!' },{ text: 'Share information freely with colleagues', correct: false, explanation: 'Only with proper authority and need-to-know.' },{ text: 'Delete all records after the engagement', correct: false, explanation: 'Records must be kept for legal/regulatory requirements.' },{ text: 'Refuse to provide information to regulators', correct: false, explanation: 'Legal/regulatory disclosure IS permitted.' }] },
  { questionText: 'When CAN client confidentiality be breached?', topic: '5 Fundamental Principles', difficulty: 'medium', syllabusRef: '1.6',
    aiExplanation: 'Confidentiality can be overridden when: (1) required by law (e.g., money laundering reports, tax fraud), (2) there is a professional duty to disclose (e.g., quality reviews), (3) the client gives permission. Disclosure to HMRC about tax fraud is a legal requirement.',
    options: [{ text: 'Never — confidentiality is absolute', correct: false, explanation: 'There are legal and professional exceptions.' },{ text: 'When required by law, professional duty, or with client consent', correct: true, explanation: 'Correct!' },{ text: 'Whenever the accountant thinks it is appropriate', correct: false, explanation: 'Must have specific legal or professional justification.' },{ text: 'Only when the client owes the accountant money', correct: false, explanation: 'Debt is not grounds for breach.' }] },
  { questionText: 'Professional behaviour requires an accountant to:', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.7',
    aiExplanation: 'Professional behaviour: comply with relevant laws and regulations, and avoid any action that discredits the profession. This includes not making disparaging references to other professionals, not making exaggerated claims about services, and behaving appropriately on social media.',
    options: [{ text: 'Comply with laws and not discredit the profession', correct: true, explanation: 'Correct!' },{ text: 'Always wear formal business attire', correct: false, explanation: 'Not about dress code.' },{ text: 'Only work with large clients', correct: false, explanation: 'Client size is irrelevant.' },{ text: 'Never make mistakes', correct: false, explanation: 'About behaviour, not perfection.' }] },
  { questionText: 'An accountant discovers their client has been overpaying tax due to an error. The principle of integrity requires:', topic: '5 Fundamental Principles', difficulty: 'medium', syllabusRef: '1.8',
    aiExplanation: 'Integrity requires honesty and straightforward dealing. The accountant should inform the client of the error and advise them to claim a refund from HMRC. Not disclosing the error would be dishonest.',
    options: [{ text: 'Ignoring the error as it benefits HMRC', correct: false, explanation: 'Integrity requires disclosure regardless of who benefits.' },{ text: 'Informing the client and advising them to claim a refund', correct: true, explanation: 'Correct!' },{ text: 'Claiming the refund without telling the client', correct: false, explanation: 'Must inform the client first.' },{ text: 'Keeping the overpayment as a fee', correct: false, explanation: 'Clearly dishonest and unethical.' }] },
  { questionText: 'A client offers an accountant a luxury holiday as a thank-you gift. This is a threat to:', topic: '5 Fundamental Principles', difficulty: 'medium', syllabusRef: '1.9',
    aiExplanation: 'Accepting a significant gift creates a self-interest threat (the accountant may feel obligated to the client) and a threat to objectivity (judgement may be influenced). Small token gifts may be acceptable but significant gifts should be declined.',
    options: [{ text: 'Objectivity', correct: true, explanation: 'Correct! Gift may influence judgement.' },{ text: 'Confidentiality', correct: false, explanation: 'No information is being disclosed.' },{ text: 'Professional competence', correct: false, explanation: 'Skills are not affected.' },{ text: 'Professional behaviour', correct: false, explanation: 'The threat is primarily to objectivity.' }] },
  { questionText: 'CPD (Continuing Professional Development) is linked to which fundamental principle?', topic: '5 Fundamental Principles', difficulty: 'easy', syllabusRef: '1.10',
    aiExplanation: 'CPD is directly linked to Professional Competence and Due Care. It requires accountants to maintain their knowledge and skills at a level where they can provide competent professional services based on current standards and legislation.',
    options: [{ text: 'Integrity', correct: false, explanation: 'About honesty.' },{ text: 'Professional competence and due care', correct: true, explanation: 'Correct!' },{ text: 'Confidentiality', correct: false, explanation: 'About information security.' },{ text: 'Objectivity', correct: false, explanation: 'About impartiality.' }] },
  // --- Threats & Safeguards (8) ---
  { questionText: 'A self-interest threat arises when:', topic: 'Threats & Safeguards', difficulty: 'easy', syllabusRef: '2.1',
    aiExplanation: 'A self-interest threat occurs when the accountant has a financial or other interest that could influence their judgement. Examples: fee dependency on one client, owning shares in a client company, fear of losing a client.',
    options: [{ text: 'The accountant has a financial interest that could influence judgement', correct: true, explanation: 'Correct!' },{ text: 'The accountant is pressured by their manager', correct: false, explanation: 'That is an intimidation threat.' },{ text: 'The accountant becomes too close to a client', correct: false, explanation: 'That is a familiarity threat.' },{ text: 'The accountant promotes a client\'s position', correct: false, explanation: 'That is an advocacy threat.' }] },
  { questionText: 'A familiarity threat occurs when:', topic: 'Threats & Safeguards', difficulty: 'easy', syllabusRef: '2.2',
    aiExplanation: 'Familiarity threat: the accountant becomes too close to a client (or colleague) and loses objectivity. Examples: long association with a client, family relationships, accepting gifts, social relationships.',
    options: [{ text: 'The accountant becomes too close to a client', correct: true, explanation: 'Correct!' },{ text: 'The accountant lacks competence', correct: false, explanation: 'Not about competence.' },{ text: 'A third party threatens the accountant', correct: false, explanation: 'That is an intimidation threat.' },{ text: 'The accountant reviews their own work', correct: false, explanation: 'That is a self-review threat.' }] },
  { questionText: 'An intimidation threat might arise from:', topic: 'Threats & Safeguards', difficulty: 'easy', syllabusRef: '2.3',
    aiExplanation: 'Intimidation threats arise when the accountant is deterred from acting objectively by actual or perceived threats. Examples: threat of dismissal, threat of litigation, a dominant personality pressuring the accountant.',
    options: [{ text: 'A client threatening to change accountants if the tax bill isn\'t reduced', correct: true, explanation: 'Correct!' },{ text: 'The accountant offering advice on tax', correct: false, explanation: 'Normal professional service.' },{ text: 'The accountant attending a client\'s party', correct: false, explanation: 'Familiarity threat, not intimidation.' },{ text: 'The accountant investing in a client', correct: false, explanation: 'Self-interest threat.' }] },
  { questionText: 'A self-review threat arises when:', topic: 'Threats & Safeguards', difficulty: 'medium', syllabusRef: '2.4',
    aiExplanation: 'Self-review: the accountant reviews their own work from a previous engagement. They may not objectively evaluate it. Example: preparing financial statements and then auditing them, or advising on an accounting treatment and then reviewing it.',
    options: [{ text: 'The accountant checks their own previous work', correct: true, explanation: 'Correct!' },{ text: 'The accountant has too many clients', correct: false, explanation: 'Not about workload.' },{ text: 'A colleague reviews the accountant\'s work', correct: false, explanation: 'That is a safeguard, not a threat.' },{ text: 'The client reviews the accountant\'s invoice', correct: false, explanation: 'Not a self-review threat.' }] },
  { questionText: 'An advocacy threat occurs when:', topic: 'Threats & Safeguards', difficulty: 'medium', syllabusRef: '2.5',
    aiExplanation: 'Advocacy: the accountant promotes a client\'s position to the point where objectivity is compromised. Example: acting as an expert witness for a client in court, or promoting a client\'s shares.',
    options: [{ text: 'The accountant promotes a client\'s position or opinion', correct: true, explanation: 'Correct!' },{ text: 'The accountant advertises their services', correct: false, explanation: 'Marketing is allowed if not misleading.' },{ text: 'The client advocates for the accountant', correct: false, explanation: 'The threat is about the accountant promoting the client.' },{ text: 'The accountant donates to charity', correct: false, explanation: 'Not an advocacy threat.' }] },
  { questionText: 'Which of the following is a safeguard against threats?', topic: 'Threats & Safeguards', difficulty: 'easy', syllabusRef: '2.6',
    aiExplanation: 'Safeguards reduce threats to an acceptable level. Examples: independent review of work, rotation of engagement partners, separation of duties, training, seeking legal advice, consulting with professional body, withdrawing from the engagement.',
    options: [{ text: 'Ignoring the threat', correct: false, explanation: 'Must address threats, not ignore them.' },{ text: 'Having an independent review of the work', correct: true, explanation: 'Correct!' },{ text: 'Increasing fees to compensate', correct: false, explanation: 'Higher fees don\'t reduce threats.' },{ text: 'Telling the client about the threat only', correct: false, explanation: 'Disclosure alone may not be sufficient.' }] },
  { questionText: 'If safeguards cannot reduce a threat to an acceptable level, the accountant should:', topic: 'Threats & Safeguards', difficulty: 'medium', syllabusRef: '2.7',
    aiExplanation: 'If no safeguard can reduce the threat: the accountant must decline or discontinue the engagement. This is the last resort when ethical principles cannot be maintained.',
    options: [{ text: 'Continue anyway and hope for the best', correct: false, explanation: 'Must not continue with unresolved threats.' },{ text: 'Decline or withdraw from the engagement', correct: true, explanation: 'Correct!' },{ text: 'Increase fees to cover the risk', correct: false, explanation: 'Fees don\'t address ethical threats.' },{ text: 'Report the client to the police', correct: false, explanation: 'Only if money laundering or criminal activity.' }] },
  { questionText: 'Fee dependency on one client is a threat because:', topic: 'Threats & Safeguards', difficulty: 'medium', syllabusRef: '2.8',
    aiExplanation: 'If a large proportion of an accountant\'s income comes from one client, losing that client would be financially devastating. This creates a self-interest threat — the accountant may compromise their principles to keep the client happy. Generally, fees from one client should not exceed 10% (AAT) or 15% (ACCA) of total fee income.',
    options: [{ text: 'The accountant may compromise principles to keep the client', correct: true, explanation: 'Correct! Self-interest threat.' },{ text: 'The accountant won\'t have enough work', correct: false, explanation: 'The concern is about objectivity, not workload.' },{ text: 'HMRC will investigate', correct: false, explanation: 'Fee dependency is an ethical issue, not a tax issue.' },{ text: 'The client will demand lower fees', correct: false, explanation: 'The threat is about compromising principles.' }] },
  // --- Ethical Conflict Resolution (4) ---
  { questionText: 'When facing an ethical dilemma, the first step should be:', topic: 'Ethical Conflict Resolution', difficulty: 'easy', syllabusRef: '3.1',
    aiExplanation: 'Step 1: Gather all relevant facts. Then: identify the ethical issues, consider the fundamental principles involved, assess threats and safeguards, explore courses of action, consult (internally then externally if needed), document everything.',
    options: [{ text: 'Immediately resign from the engagement', correct: false, explanation: 'Resignation is a last resort, not the first step.' },{ text: 'Gather all relevant facts', correct: true, explanation: 'Correct!' },{ text: 'Report the client to HMRC', correct: false, explanation: 'Not all dilemmas involve tax fraud.' },{ text: 'Contact a lawyer', correct: false, explanation: 'May be needed later, but start with the facts.' }] },
  { questionText: 'An accountant suspects their employer is committing fraud. They should:', topic: 'Ethical Conflict Resolution', difficulty: 'medium', syllabusRef: '3.2',
    aiExplanation: 'Follow internal procedures first: raise concerns with a supervisor or compliance officer. If not resolved internally, consider external reporting (e.g., to professional body, regulator, or HMRC). Document everything. Whistleblowing protection may apply under the Public Interest Disclosure Act 1998.',
    options: [{ text: 'Ignore it — loyalty to employer comes first', correct: false, explanation: 'Ethical duties override employer loyalty.' },{ text: 'Follow internal procedures, then external reporting if unresolved', correct: true, explanation: 'Correct!' },{ text: 'Immediately contact the press', correct: false, explanation: 'Not the appropriate channel.' },{ text: 'Quit without telling anyone', correct: false, explanation: 'Has a duty to report, not just leave.' }] },
  { questionText: 'If an accountant discovers a client has committed a criminal offence, they:', topic: 'Ethical Conflict Resolution', difficulty: 'hard', syllabusRef: '3.3',
    aiExplanation: 'If a criminal offence is suspected (especially money laundering or terrorist financing), the accountant MUST report to the National Crime Agency (NCA) via a Suspicious Activity Report (SAR). They must NOT tip off the client. This overrides confidentiality.',
    options: [{ text: 'Must keep it confidential', correct: false, explanation: 'Legal reporting requirements override confidentiality.' },{ text: 'Must report to the NCA and not tip off the client', correct: true, explanation: 'Correct!' },{ text: 'Should advise the client to turn themselves in', correct: false, explanation: 'This could be tipping off, which is illegal.' },{ text: 'Has no obligation to report', correct: false, explanation: 'Legal duty to report suspected money laundering.' }] },
  { questionText: 'Tipping off means:', topic: 'Ethical Conflict Resolution', difficulty: 'easy', syllabusRef: '3.4',
    aiExplanation: 'Tipping off is informing someone (directly or indirectly) that a SAR has been filed or that an investigation is taking place. It is a criminal offence under the Proceeds of Crime Act 2002. The accountant must not alert the client that they have reported suspicions.',
    options: [{ text: 'Alerting someone that a suspicious activity report has been made', correct: true, explanation: 'Correct! Criminal offence.' },{ text: 'Giving a tip to a colleague about a client', correct: false, explanation: 'Not the legal meaning of tipping off.' },{ text: 'Recommending a client to another accountant', correct: false, explanation: 'Normal professional referral.' },{ text: 'Providing tax tips to clients', correct: false, explanation: 'Normal tax advice.' }] },
  // --- Money Laundering (6) ---
  { questionText: 'Money laundering involves:', topic: 'Money Laundering Regulations', difficulty: 'easy', syllabusRef: '4.1',
    aiExplanation: 'Money laundering is the process of making illegally-obtained money appear legitimate. Three stages: Placement (introducing criminal funds into the system), Layering (complex transactions to disguise the trail), Integration (funds re-enter the economy appearing legitimate).',
    options: [{ text: 'Making illegal money appear legitimate', correct: true, explanation: 'Correct!' },{ text: 'Transferring money between bank accounts', correct: false, explanation: 'Transfers are normal; money laundering is about disguising criminal proceeds.' },{ text: 'Avoiding tax legally', correct: false, explanation: 'Tax avoidance is different from money laundering.' },{ text: 'Using foreign currency', correct: false, explanation: 'Currency exchange is normal business.' }] },
  { questionText: 'The three stages of money laundering are:', topic: 'Money Laundering Regulations', difficulty: 'easy', syllabusRef: '4.2',
    aiExplanation: 'Placement: introducing dirty money (e.g., cash deposits). Layering: complex transactions to obscure the trail (e.g., multiple transfers, shell companies). Integration: clean-looking money re-enters the economy (e.g., property purchases, investments).',
    options: [{ text: 'Placement, Layering, Integration', correct: true, explanation: 'Correct!' },{ text: 'Collection, Transfer, Spending', correct: false, explanation: 'Not the official terms.' },{ text: 'Earning, Saving, Investing', correct: false, explanation: 'Normal financial activities.' },{ text: 'Planning, Execution, Completion', correct: false, explanation: 'Not the AML terms.' }] },
  { questionText: 'Under the Proceeds of Crime Act 2002, which is a money laundering offence?', topic: 'Money Laundering Regulations', difficulty: 'medium', syllabusRef: '4.3',
    aiExplanation: 'Three main offences: (1) Concealing criminal property (s327), (2) Arranging the acquisition/use/control of criminal property (s328), (3) Acquiring/using/possessing criminal property (s329). Plus: failure to disclose (s330) and tipping off (s333A).',
    options: [{ text: 'Failure to disclose knowledge or suspicion of money laundering', correct: true, explanation: 'Correct! s330 offence.' },{ text: 'Filing tax returns late', correct: false, explanation: 'A tax offence, not money laundering.' },{ text: 'Making an error in financial statements', correct: false, explanation: 'An accounting error, not ML.' },{ text: 'Charging high fees', correct: false, explanation: 'Not an offence.' }] },
  { questionText: 'Customer Due Diligence (CDD) requires accountants to:', topic: 'Money Laundering Regulations', difficulty: 'easy', syllabusRef: '4.4',
    aiExplanation: 'CDD (also called KYC — Know Your Customer): verify the identity of clients before providing services. This includes checking ID documents (passport, driving licence), proof of address, understanding the nature of the business relationship, and ongoing monitoring.',
    options: [{ text: 'Verify the identity of clients', correct: true, explanation: 'Correct!' },{ text: 'Check clients\' tax returns for accuracy', correct: false, explanation: 'That is normal professional work.' },{ text: 'Investigate all client transactions', correct: false, explanation: 'CDD is about identity verification.' },{ text: 'Only work with clients they know personally', correct: false, explanation: 'CDD applies to all clients, personal knowledge is not enough.' }] },
  { questionText: 'Enhanced Due Diligence (EDD) is required when:', topic: 'Money Laundering Regulations', difficulty: 'medium', syllabusRef: '4.5',
    aiExplanation: 'EDD is required for higher-risk situations: Politically Exposed Persons (PEPs), complex/unusual transactions, clients from high-risk countries, anonymous or remote transactions. Extra checks and senior management approval are needed.',
    options: [{ text: 'The client is a Politically Exposed Person (PEP)', correct: true, explanation: 'Correct!' },{ text: 'All clients regardless of risk', correct: false, explanation: 'Standard CDD for normal risk; EDD for high risk.' },{ text: 'The client pays in cash', correct: false, explanation: 'Cash payments may trigger suspicion but EDD is specifically for high-risk factors.' },{ text: 'The fee exceeds £10,000', correct: false, explanation: 'No fee threshold for EDD.' }] },
  { questionText: 'A Suspicious Activity Report (SAR) is submitted to:', topic: 'Money Laundering Regulations', difficulty: 'easy', syllabusRef: '4.6',
    aiExplanation: 'SARs are submitted to the National Crime Agency (NCA), usually via the firm\'s Money Laundering Reporting Officer (MLRO). The MLRO is the designated person within the firm responsible for receiving and evaluating internal reports.',
    options: [{ text: 'HMRC', correct: false, explanation: 'Tax matters go to HMRC; SARs go to NCA.' },{ text: 'The National Crime Agency (NCA)', correct: true, explanation: 'Correct!' },{ text: 'The police', correct: false, explanation: 'NCA handles SARs, not local police.' },{ text: 'The client\'s bank', correct: false, explanation: 'Not the client\'s bank.' }] },
  // --- Whistleblowing & CPD (4) ---
  { questionText: 'Whistleblowing is protected by:', topic: 'Whistleblowing', difficulty: 'easy', syllabusRef: '5.1',
    aiExplanation: 'The Public Interest Disclosure Act 1998 (PIDA) protects workers who make qualifying disclosures about wrongdoing from dismissal or detriment. The disclosure must be in good faith and about one of the categories of wrongdoing specified in the Act.',
    options: [{ text: 'The Public Interest Disclosure Act 1998', correct: true, explanation: 'Correct!' },{ text: 'The Companies Act 2006', correct: false, explanation: 'Covers company law, not whistleblowing protection.' },{ text: 'GDPR', correct: false, explanation: 'Covers data protection.' },{ text: 'There is no legal protection', correct: false, explanation: 'PIDA provides protection.' }] },
  { questionText: 'A qualifying disclosure under whistleblowing legislation includes:', topic: 'Whistleblowing', difficulty: 'medium', syllabusRef: '5.2',
    aiExplanation: 'Qualifying disclosures cover: criminal offences, failure to comply with legal obligations, miscarriages of justice, health and safety dangers, environmental damage, and deliberate concealment of any of these.',
    options: [{ text: 'A complaint about pay or working conditions', correct: false, explanation: 'Employment grievances, not whistleblowing.' },{ text: 'Disclosure of a criminal offence or danger to health and safety', correct: true, explanation: 'Correct!' },{ text: 'Any disagreement with management', correct: false, explanation: 'Must relate to specific categories of wrongdoing.' },{ text: 'A request for a pay rise', correct: false, explanation: 'Not whistleblowing.' }] },
  { questionText: 'AAT members must complete CPD to:', topic: 'CPD Requirements', difficulty: 'easy', syllabusRef: '6.1',
    aiExplanation: 'CPD ensures accountants maintain and develop their knowledge, skills, and competence. It is a requirement of membership and linked to the fundamental principle of professional competence and due care.',
    options: [{ text: 'Maintain professional competence and skills', correct: true, explanation: 'Correct!' },{ text: 'Increase their annual income', correct: false, explanation: 'Not the purpose of CPD.' },{ text: 'Satisfy their employer only', correct: false, explanation: 'Professional body requirement.' },{ text: 'Avoid paying membership fees', correct: false, explanation: 'CPD and fees are separate requirements.' }] },
  { questionText: 'Which of the following would count as CPD?', topic: 'CPD Requirements', difficulty: 'easy', syllabusRef: '6.2',
    aiExplanation: 'CPD can be: attending courses/webinars, reading technical articles, on-the-job training, mentoring, studying for further qualifications, attending professional events. It should be relevant and documented.',
    options: [{ text: 'Attending a technical webinar on tax updates', correct: true, explanation: 'Correct!' },{ text: 'Watching entertainment TV', correct: false, explanation: 'Must be professionally relevant.' },{ text: 'Going on holiday', correct: false, explanation: 'Not professional development.' },{ text: 'Shopping for office supplies', correct: false, explanation: 'Not development activity.' }] },
];

async function main() {
  console.log('\n🎓 Seeding L3 ETHC...\n');
  await seedModule('ETHC', ETHC);
  console.log('\n✅ Done!');
}
main().catch(console.error).finally(() => prisma.$disconnect());
