/**
 * Level 3 AVBK — Advanced Bookkeeping (40 questions)
 * Run: npx tsx prisma/seed-questions-l3-avbk.ts
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
interface QS { questionText: string; topic: string; difficulty: 'easy'|'medium'|'hard'; syllabusRef: string; aiExplanation: string; options: { text: string; correct: boolean; explanation: string }[]; }
async function seedModule(code: string, questions: QS[]) {
  const mod = await (prisma as any).examModule.findFirst({ where: { code } });
  if (!mod) { console.log(`  ⚠️ ${code} not found`); return; }
  const existing = await (prisma as any).question.count({ where: { moduleId: mod.id } });
  let added = 0;
  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const dup = await (prisma as any).question.findFirst({ where: { moduleId: mod.id, questionText: q.questionText } });
    if (dup) continue;
    const created = await (prisma as any).question.create({
      data: { moduleId: mod.id, questionText: q.questionText, topic: q.topic, difficulty: q.difficulty, syllabusRef: q.syllabusRef, aiExplanation: q.aiExplanation, sortOrder: existing + i + 1 },
    });
    for (let j = 0; j < q.options.length; j++) {
      await (prisma as any).questionOption.create({
        data: { questionId: created.id, optionText: q.options[j].text, isCorrect: q.options[j].correct, explanation: q.options[j].explanation, sortOrder: j + 1 },
      });
    }
    added++;
  }
  console.log(`  ✅ ${code}: ${added} new (${existing} existed)`);
}

const AVBK: QS[] = [
  // --- Accruals & Prepayments (10) ---
  { questionText: 'A business has a year end of 31 December. Rent of £12,000 is paid annually on 1 April. What is the prepayment at 31 December?', topic: 'Accruals & Prepayments', difficulty: 'medium', syllabusRef: '1.1',
    aiExplanation: 'Rent £12,000 covers 1 Apr to 31 Mar (12 months). At 31 Dec, 9 months used (Apr-Dec), 3 months prepaid (Jan-Mar). Prepayment = 3/12 × £12,000 = £3,000.',
    options: [{ text: '£3,000', correct: true, explanation: 'Correct! 3 months prepaid × £1,000/month.' },{ text: '£9,000', correct: false, explanation: 'That is the expense for the year, not the prepayment.' },{ text: '£1,000', correct: false, explanation: 'Only 1 month — but 3 months are prepaid.' },{ text: '£12,000', correct: false, explanation: 'The full amount — not all is prepaid.' }] },
  { questionText: 'Electricity bill for Q4 (Oct-Dec) of £900 has not been received at year end 31 December. The accrual is:', topic: 'Accruals & Prepayments', difficulty: 'easy', syllabusRef: '1.2',
    aiExplanation: 'The electricity was consumed in Oct-Dec but not yet billed. Under the accruals concept, the expense must be recognised in the period it relates to. Accrual = £900.',
    options: [{ text: '£900', correct: true, explanation: 'Correct! Full quarter accrued.' },{ text: '£300', correct: false, explanation: 'Only one month — but all three months need accruing.' },{ text: '£0', correct: false, explanation: 'Must accrue the expense even though no bill received.' },{ text: '£600', correct: false, explanation: 'Two months — but all three months are unpaid.' }] },
  { questionText: 'The double entry to record an accrual for electricity £900 at year end is:', topic: 'Accruals & Prepayments', difficulty: 'easy', syllabusRef: '1.3',
    aiExplanation: 'DR Electricity (expense) £900, CR Accruals (liability) £900. The expense increases and a liability is created for the amount owed.',
    options: [{ text: 'DR Electricity £900, CR Accruals £900', correct: true, explanation: 'Correct!' },{ text: 'DR Accruals £900, CR Electricity £900', correct: false, explanation: 'Reversed.' },{ text: 'DR Electricity £900, CR Bank £900', correct: false, explanation: 'Not yet paid — no bank entry.' },{ text: 'DR Prepayments £900, CR Electricity £900', correct: false, explanation: 'This is an accrual, not a prepayment.' }] },
  { questionText: 'Insurance paid £2,400 for the year 1 July to 30 June. Year end 31 March. What is the P&L charge?', topic: 'Accruals & Prepayments', difficulty: 'medium', syllabusRef: '1.4',
    aiExplanation: 'Period: 1 Jul to 30 Jun = 12 months at £200/month. Year end 31 Mar: 9 months used (Jul-Mar). P&L charge = 9 × £200 = £1,800. Prepayment = 3 × £200 = £600.',
    options: [{ text: '£1,800', correct: true, explanation: 'Correct! 9 months × £200.' },{ text: '£2,400', correct: false, explanation: 'Full payment — but 3 months are prepaid.' },{ text: '£600', correct: false, explanation: 'That is the prepayment, not the expense.' },{ text: '£1,200', correct: false, explanation: 'Only 6 months — should be 9.' }] },
  { questionText: 'Where does a prepayment appear in the financial statements?', topic: 'Accruals & Prepayments', difficulty: 'easy', syllabusRef: '1.5',
    aiExplanation: 'A prepayment is an amount paid in advance — it is a current asset (the business has a right to receive the service/benefit in the future). It appears under current assets on the statement of financial position.',
    options: [{ text: 'Current liability', correct: false, explanation: 'Accruals are current liabilities, not prepayments.' },{ text: 'Current asset', correct: true, explanation: 'Correct! Prepayments are assets.' },{ text: 'Non-current asset', correct: false, explanation: 'Prepayments are short-term, so current.' },{ text: 'Expense in P&L only', correct: false, explanation: 'The prepaid portion is NOT in P&L.' }] },
  { questionText: 'An accrual appears on the statement of financial position as a:', topic: 'Accruals & Prepayments', difficulty: 'easy', syllabusRef: '1.6',
    aiExplanation: 'An accrual is an amount owed but not yet paid or billed. It is a current liability — the business has an obligation to pay.',
    options: [{ text: 'Current asset', correct: false, explanation: 'Prepayments are assets; accruals are liabilities.' },{ text: 'Current liability', correct: true, explanation: 'Correct!' },{ text: 'Non-current liability', correct: false, explanation: 'Accruals are short-term.' },{ text: 'Equity', correct: false, explanation: 'Accruals are not equity.' }] },
  { questionText: 'Opening accrual for wages is £500. Total wages paid during the year £24,000. Closing accrual £700. P&L wages expense?', topic: 'Accruals & Prepayments', difficulty: 'hard', syllabusRef: '1.7',
    aiExplanation: 'P&L expense = Cash paid - Opening accrual + Closing accrual = £24,000 - £500 + £700 = £24,200. Opening accrual was for last year (reduce this year\'s charge). Closing accrual is for this year (add to charge).',
    options: [{ text: '£24,200', correct: true, explanation: 'Correct! £24,000 - £500 + £700.' },{ text: '£23,800', correct: false, explanation: 'Added opening and subtracted closing — reversed.' },{ text: '£24,000', correct: false, explanation: 'Ignores accruals.' },{ text: '£25,200', correct: false, explanation: 'Added both accruals.' }] },
  { questionText: 'Opening prepayment for rent £400. Rent paid during year £4,800. Closing prepayment £600. P&L rent expense?', topic: 'Accruals & Prepayments', difficulty: 'hard', syllabusRef: '1.8',
    aiExplanation: 'P&L expense = Cash paid + Opening prepayment - Closing prepayment = £4,800 + £400 - £600 = £4,600. Opening prepayment was for this year (add). Closing prepayment is for next year (subtract).',
    options: [{ text: '£4,600', correct: true, explanation: 'Correct! £4,800 + £400 - £600.' },{ text: '£5,000', correct: false, explanation: 'Added opening but forgot to subtract closing.' },{ text: '£5,800', correct: false, explanation: 'Added both.' },{ text: '£4,800', correct: false, explanation: 'Ignores prepayments.' }] },
  { questionText: 'The accruals (matching) concept requires that:', topic: 'Accruals & Prepayments', difficulty: 'easy', syllabusRef: '1.9',
    aiExplanation: 'The accruals concept (matching principle) requires revenue and expenses to be recognised in the period to which they relate, not when cash is received or paid. This ensures the P&L reflects the true economic activity of the period.',
    options: [{ text: 'Income and expenses are recorded when cash changes hands', correct: false, explanation: 'That is the cash basis, not accruals.' },{ text: 'Income and expenses are matched to the period they relate to', correct: true, explanation: 'Correct!' },{ text: 'All expenses are paid before year end', correct: false, explanation: 'Accruals exist precisely because not all are paid.' },{ text: 'Revenue is only recognised when received', correct: false, explanation: 'Revenue is recognised when earned, not received.' }] },
  { questionText: 'A business pays £600 rates on 1 April for the half-year to 30 September. Year end is 31 July. How much is the prepayment?', topic: 'Accruals & Prepayments', difficulty: 'medium', syllabusRef: '1.10',
    aiExplanation: '£600 for 6 months (Apr-Sep) = £100/month. At 31 Jul: 4 months used (Apr-Jul), 2 months prepaid (Aug-Sep). Prepayment = 2 × £100 = £200.',
    options: [{ text: '£200', correct: true, explanation: 'Correct! 2 months × £100.' },{ text: '£400', correct: false, explanation: 'That is the expense (4 months), not the prepayment.' },{ text: '£100', correct: false, explanation: 'Only 1 month prepaid — but Aug and Sep both prepaid.' },{ text: '£300', correct: false, explanation: '3 months — but only Aug and Sep are prepaid.' }] },
  // --- Depreciation (10) ---
  { questionText: 'A machine costs £20,000 with a residual value of £2,000 and useful life of 5 years. Annual straight-line depreciation?', topic: 'Depreciation Methods', difficulty: 'easy', syllabusRef: '2.1',
    aiExplanation: 'Straight-line: (Cost - Residual value) ÷ Useful life = (£20,000 - £2,000) ÷ 5 = £3,600 per year.',
    options: [{ text: '£3,600', correct: true, explanation: 'Correct! (£20,000-£2,000)÷5.' },{ text: '£4,000', correct: false, explanation: 'Ignores residual value.' },{ text: '£18,000', correct: false, explanation: 'Total depreciation, not annual.' },{ text: '£2,000', correct: false, explanation: 'That is the residual value.' }] },
  { questionText: 'Using reducing balance at 25%, a vehicle costs £16,000. Depreciation in year 2?', topic: 'Depreciation Methods', difficulty: 'medium', syllabusRef: '2.2',
    aiExplanation: 'Year 1: 25% × £16,000 = £4,000. NBV = £12,000. Year 2: 25% × £12,000 = £3,000.',
    options: [{ text: '£3,000', correct: true, explanation: 'Correct! 25% × £12,000 (NBV after year 1).' },{ text: '£4,000', correct: false, explanation: 'That is year 1 depreciation.' },{ text: '£2,250', correct: false, explanation: 'That would be year 3.' },{ text: '£12,000', correct: false, explanation: 'That is the NBV after year 1.' }] },
  { questionText: 'The double entry for recording depreciation is:', topic: 'Depreciation Methods', difficulty: 'easy', syllabusRef: '2.3',
    aiExplanation: 'DR Depreciation Expense (P&L — increases expense), CR Accumulated Depreciation (reduces NBV on SOFP). The asset account itself is NOT credited; instead, a separate contra-asset account is used.',
    options: [{ text: 'DR Depreciation Expense, CR Accumulated Depreciation', correct: true, explanation: 'Correct!' },{ text: 'DR Asset, CR Depreciation Expense', correct: false, explanation: 'Reversed and wrong accounts.' },{ text: 'DR Accumulated Depreciation, CR Bank', correct: false, explanation: 'Depreciation is not a cash transaction.' },{ text: 'DR Depreciation Expense, CR Asset', correct: false, explanation: 'We credit accumulated depreciation, not the asset directly.' }] },
  { questionText: 'Net book value (NBV) of an asset is calculated as:', topic: 'Depreciation Methods', difficulty: 'easy', syllabusRef: '2.4',
    aiExplanation: 'NBV = Cost - Accumulated Depreciation. It represents the remaining value of the asset in the books after accounting for wear and tear.',
    options: [{ text: 'Cost - Accumulated Depreciation', correct: true, explanation: 'Correct!' },{ text: 'Cost - Annual Depreciation', correct: false, explanation: 'Must use total accumulated depreciation, not just one year.' },{ text: 'Cost + Accumulated Depreciation', correct: false, explanation: 'Depreciation reduces value, not increases it.' },{ text: 'Market value of the asset', correct: false, explanation: 'NBV is a book value, not market value.' }] },
  { questionText: 'Which depreciation method gives higher charges in the early years?', topic: 'Depreciation Methods', difficulty: 'easy', syllabusRef: '2.5',
    aiExplanation: 'Reducing balance gives higher depreciation in early years (applied to a decreasing NBV). Straight-line gives equal charges every year. Reducing balance better reflects assets that lose value quickly early on (e.g., vehicles).',
    options: [{ text: 'Straight-line', correct: false, explanation: 'Same charge every year.' },{ text: 'Reducing balance', correct: true, explanation: 'Correct! Higher early, lower later.' },{ text: 'Both give the same', correct: false, explanation: 'Different patterns of depreciation.' },{ text: 'Units of production', correct: false, explanation: 'Depends on usage, not time.' }] },
  { questionText: 'Equipment cost £10,000, accumulated depreciation £7,500. It is sold for £3,000. Profit or loss on disposal?', topic: 'Disposal of Non-Current Assets', difficulty: 'medium', syllabusRef: '3.1',
    aiExplanation: 'NBV = £10,000 - £7,500 = £2,500. Sale proceeds = £3,000. Profit on disposal = £3,000 - £2,500 = £500.',
    options: [{ text: 'Profit £500', correct: true, explanation: 'Correct! £3,000 - £2,500 NBV.' },{ text: 'Loss £500', correct: false, explanation: 'Proceeds exceed NBV = profit.' },{ text: 'Profit £3,000', correct: false, explanation: 'Must deduct NBV from proceeds.' },{ text: 'Loss £7,000', correct: false, explanation: 'Incorrect calculation.' }] },
  { questionText: 'The disposal account entries for the above scenario include:', topic: 'Disposal of Non-Current Assets', difficulty: 'hard', syllabusRef: '3.2',
    aiExplanation: 'Disposal account: DR Disposal with cost £10,000, CR Disposal with accumulated dep £7,500, CR Disposal with sale proceeds £3,000. Balance = £10,000 - £7,500 - £3,000 = -£500 (credit = profit).',
    options: [{ text: 'DR Disposal £10,000 (cost), CR Disposal £7,500 (acc dep) + £3,000 (proceeds)', correct: true, explanation: 'Correct! Credit balance of £500 = profit.' },{ text: 'DR Disposal £3,000, CR Bank £3,000', correct: false, explanation: 'Incomplete — must also transfer cost and accumulated dep.' },{ text: 'DR Bank £3,000, CR Asset £3,000', correct: false, explanation: 'Must use the disposal account.' },{ text: 'DR Disposal £2,500, CR Bank £3,000', correct: false, explanation: 'Must transfer full cost and accumulated depreciation separately.' }] },
  { questionText: 'A van cost £15,000 and has been depreciated for 3 years at 20% reducing balance. NBV at end of year 3?', topic: 'Depreciation Methods', difficulty: 'hard', syllabusRef: '2.6',
    aiExplanation: 'Y1: £15,000×20%=£3,000, NBV=£12,000. Y2: £12,000×20%=£2,400, NBV=£9,600. Y3: £9,600×20%=£1,920, NBV=£7,680.',
    options: [{ text: '£7,680', correct: true, explanation: 'Correct! £15,000 × 0.8³ = £7,680.' },{ text: '£6,000', correct: false, explanation: 'Would be straight-line (£5,000/yr × 3 = £9,000 dep, but that gives £6,000 only if no residual).' },{ text: '£9,600', correct: false, explanation: 'That is NBV after year 2.' },{ text: '£9,000', correct: false, explanation: 'Incorrect calculation.' }] },
  { questionText: 'When should a business change its depreciation method?', topic: 'Depreciation Methods', difficulty: 'medium', syllabusRef: '2.7',
    aiExplanation: 'A change in depreciation method should only be made if it gives a more accurate reflection of the pattern in which the asset\'s economic benefits are consumed. It is a change in accounting estimate under IAS 8, applied prospectively (not retrospectively).',
    options: [{ text: 'Every year for consistency', correct: false, explanation: 'Consistency requires using the same method unless there is good reason to change.' },{ text: 'When it better reflects the pattern of economic benefits', correct: true, explanation: 'Correct!' },{ text: 'When the business makes a loss', correct: false, explanation: 'Losses are not a valid reason to change.' },{ text: 'Never — once chosen it cannot be changed', correct: false, explanation: 'It can be changed with proper justification.' }] },
  { questionText: 'An asset with zero residual value is depreciated over 4 years straight-line. It cost £8,000 and was bought on 1 October. Year end 31 December. Year 1 depreciation (pro-rata)?', topic: 'Depreciation Methods', difficulty: 'hard', syllabusRef: '2.8',
    aiExplanation: 'Annual depreciation = £8,000 ÷ 4 = £2,000. Owned for 3 months in year 1 (Oct-Dec). Pro-rata: 3/12 × £2,000 = £500.',
    options: [{ text: '£500', correct: true, explanation: 'Correct! 3/12 × £2,000.' },{ text: '£2,000', correct: false, explanation: 'Full year — but only owned 3 months.' },{ text: '£1,500', correct: false, explanation: 'Would be 9 months.' },{ text: '£667', correct: false, explanation: 'Incorrect fraction.' }] },
  // --- Irrecoverable Debts & Allowances (8) ---
  { questionText: 'A business writes off a debt of £300. The double entry is:', topic: 'Irrecoverable Debts', difficulty: 'easy', syllabusRef: '4.1',
    aiExplanation: 'DR Irrecoverable Debts Expense £300 (P&L expense), CR Trade Receivables £300 (remove the debt from the ledger).',
    options: [{ text: 'DR Irrecoverable Debts £300, CR Trade Receivables £300', correct: true, explanation: 'Correct!' },{ text: 'DR Trade Receivables £300, CR Bank £300', correct: false, explanation: 'No cash involved in a write-off.' },{ text: 'DR Bank £300, CR Irrecoverable Debts £300', correct: false, explanation: 'No cash received.' },{ text: 'DR Irrecoverable Debts £300, CR Bank £300', correct: false, explanation: 'Bank not involved.' }] },
  { questionText: 'Trade receivables are £50,000. The allowance for doubtful debts is set at 5%. What is the allowance?', topic: 'Allowance for Doubtful Debts', difficulty: 'easy', syllabusRef: '4.2',
    aiExplanation: 'Allowance = 5% × £50,000 = £2,500. This is a provision against receivables that may not be collected. It reduces the receivables figure on the SOFP.',
    options: [{ text: '£2,500', correct: true, explanation: 'Correct! 5% × £50,000.' },{ text: '£5,000', correct: false, explanation: '10%, not 5%.' },{ text: '£47,500', correct: false, explanation: 'That is net receivables, not the allowance.' },{ text: '£50,000', correct: false, explanation: 'That is total receivables.' }] },
  { questionText: 'Last year\'s allowance was £2,000. This year it needs to be £2,500. P&L charge for the increase?', topic: 'Allowance for Doubtful Debts', difficulty: 'medium', syllabusRef: '4.3',
    aiExplanation: 'Only the INCREASE in the allowance is charged to P&L. Increase = £2,500 - £2,000 = £500. DR Irrecoverable Debts Expense £500, CR Allowance for Doubtful Debts £500.',
    options: [{ text: '£500', correct: true, explanation: 'Correct! Only the increase.' },{ text: '£2,500', correct: false, explanation: 'That is the total allowance, not the P&L charge.' },{ text: '£2,000', correct: false, explanation: 'That was last year\'s allowance.' },{ text: '£4,500', correct: false, explanation: 'Added both years together.' }] },
  { questionText: 'If the allowance decreases from £3,000 to £1,800, the P&L effect is:', topic: 'Allowance for Doubtful Debts', difficulty: 'medium', syllabusRef: '4.4',
    aiExplanation: 'A decrease in the allowance is CREDITED to P&L (reduces the expense/increases profit). DR Allowance £1,200, CR Irrecoverable Debts Expense £1,200.',
    options: [{ text: 'Income/credit of £1,200', correct: true, explanation: 'Correct! Decrease reduces the expense.' },{ text: 'Expense of £1,200', correct: false, explanation: 'A decrease is a credit, not an expense.' },{ text: 'Expense of £1,800', correct: false, explanation: 'That is the new allowance balance.' },{ text: 'No P&L effect', correct: false, explanation: 'Changes in the allowance do affect P&L.' }] },
  { questionText: 'Net trade receivables on the SOFP with receivables of £40,000 and an allowance of £2,000 are:', topic: 'Allowance for Doubtful Debts', difficulty: 'easy', syllabusRef: '4.5',
    aiExplanation: 'Net receivables = Gross receivables - Allowance for doubtful debts = £40,000 - £2,000 = £38,000.',
    options: [{ text: '£38,000', correct: true, explanation: 'Correct!' },{ text: '£40,000', correct: false, explanation: 'Must deduct the allowance.' },{ text: '£42,000', correct: false, explanation: 'Added instead of subtracted.' },{ text: '£2,000', correct: false, explanation: 'That is just the allowance.' }] },
  { questionText: 'A previously written-off debt of £400 is unexpectedly recovered. The double entry is:', topic: 'Irrecoverable Debts', difficulty: 'medium', syllabusRef: '4.6',
    aiExplanation: 'Two entries needed: (1) Reinstate the debt: DR Trade Receivables £400, CR Irrecoverable Debts Recovered £400. (2) Record the cash: DR Bank £400, CR Trade Receivables £400. Or combined: DR Bank £400, CR Irrecoverable Debts Recovered £400.',
    options: [{ text: 'DR Bank £400, CR Irrecoverable Debts Recovered £400', correct: true, explanation: 'Correct! Cash received, income recognised.' },{ text: 'DR Bank £400, CR Trade Receivables £400', correct: false, explanation: 'The debt was written off — no receivable exists to credit.' },{ text: 'DR Irrecoverable Debts £400, CR Bank £400', correct: false, explanation: 'Completely reversed.' },{ text: 'No entry needed', correct: false, explanation: 'The recovery must be recorded.' }] },
  { questionText: 'The allowance for doubtful debts is based on the concept of:', topic: 'Allowance for Doubtful Debts', difficulty: 'easy', syllabusRef: '4.7',
    aiExplanation: 'The allowance is based on prudence — recognising potential losses before they are confirmed. It ensures receivables are not overstated on the SOFP. It also applies the accruals concept by matching the estimated bad debt expense to the period of the sale.',
    options: [{ text: 'Prudence', correct: true, explanation: 'Correct! Anticipating potential losses.' },{ text: 'Going concern', correct: false, explanation: 'Going concern is about the business continuing to operate.' },{ text: 'Historical cost', correct: false, explanation: 'Relates to recording assets at purchase price.' },{ text: 'Materiality', correct: false, explanation: 'Materiality is about significance, not provisioning.' }] },
  { questionText: 'Specific allowances are made for:', topic: 'Allowance for Doubtful Debts', difficulty: 'easy', syllabusRef: '4.8',
    aiExplanation: 'A specific allowance targets individually identified debts that are considered doubtful (e.g., a known customer in financial difficulty). A general allowance is a percentage applied to all remaining receivables.',
    options: [{ text: 'A percentage of all receivables', correct: false, explanation: 'That is a general allowance.' },{ text: 'Individually identified doubtful debts', correct: true, explanation: 'Correct!' },{ text: 'All customers equally', correct: false, explanation: 'Specific means targeting individual debts.' },{ text: 'Only new customers', correct: false, explanation: 'Based on payment likelihood, not customer age.' }] },
  // --- Extended Trial Balance (6) ---
  { questionText: 'In an extended trial balance (ETB), adjustments are made in which columns?', topic: 'Extended Trial Balance', difficulty: 'easy', syllabusRef: '5.1',
    aiExplanation: 'The ETB has columns: Ledger Balances (DR/CR), Adjustments (DR/CR), Statement of P&L (DR/CR), Statement of Financial Position (DR/CR). Year-end adjustments go in the Adjustments columns.',
    options: [{ text: 'Ledger balance columns', correct: false, explanation: 'Original balances go there.' },{ text: 'Adjustment columns', correct: true, explanation: 'Correct!' },{ text: 'P&L columns directly', correct: false, explanation: 'Adjustments go in the adjustment columns first.' },{ text: 'A separate journal book', correct: false, explanation: 'Adjustments are recorded on the ETB itself.' }] },
  { questionText: 'On the ETB, where does closing inventory appear?', topic: 'Extended Trial Balance', difficulty: 'medium', syllabusRef: '5.2',
    aiExplanation: 'Closing inventory appears in TWO places: (1) CR in the P&L columns (reduces cost of sales), (2) DR in the SOFP columns (current asset). This dual entry is unique to closing inventory on the ETB.',
    options: [{ text: 'P&L only', correct: false, explanation: 'Also appears on SOFP.' },{ text: 'SOFP only', correct: false, explanation: 'Also appears on P&L.' },{ text: 'P&L credit AND SOFP debit', correct: true, explanation: 'Correct! Appears in both.' },{ text: 'P&L debit AND SOFP credit', correct: false, explanation: 'Wrong sides — CR in P&L, DR in SOFP.' }] },
  { questionText: 'A depreciation adjustment of £1,500 on the ETB is shown as:', topic: 'Extended Trial Balance', difficulty: 'medium', syllabusRef: '5.3',
    aiExplanation: 'DR Depreciation Expense £1,500 (goes to P&L), CR Accumulated Depreciation £1,500 (goes to SOFP). In the adjustments columns: DR in one line, CR in another. Then carried across to the appropriate statement columns.',
    options: [{ text: 'DR Depreciation Expense, CR Accumulated Depreciation', correct: true, explanation: 'Correct!' },{ text: 'DR Accumulated Depreciation, CR Depreciation Expense', correct: false, explanation: 'Reversed.' },{ text: 'DR Asset, CR Bank', correct: false, explanation: 'Depreciation is not a cash or asset entry.' },{ text: 'Only in the P&L columns', correct: false, explanation: 'Accumulated dep goes to SOFP.' }] },
  { questionText: 'If the P&L columns on the ETB show total debits £85,000 and credits £95,000, the business has made a:', topic: 'Extended Trial Balance', difficulty: 'easy', syllabusRef: '5.4',
    aiExplanation: 'P&L: Credits (income) exceed Debits (expenses) = Profit. Profit = £95,000 - £85,000 = £10,000. If debits exceeded credits, it would be a loss.',
    options: [{ text: 'Profit of £10,000', correct: true, explanation: 'Correct! Income £95k > Expenses £85k.' },{ text: 'Loss of £10,000', correct: false, explanation: 'Credits exceed debits = profit.' },{ text: 'Profit of £180,000', correct: false, explanation: 'Added both columns.' },{ text: 'Cannot be determined', correct: false, explanation: 'Profit = credits - debits in P&L.' }] },
  { questionText: 'The profit/loss figure from the P&L columns is transferred to the SOFP columns as:', topic: 'Extended Trial Balance', difficulty: 'medium', syllabusRef: '5.5',
    aiExplanation: 'Profit is a credit balance (it increases capital/equity). It appears as a CREDIT in the SOFP columns. A loss would be a debit. This ensures both statement columns balance.',
    options: [{ text: 'A debit in SOFP', correct: false, explanation: 'Profit is a credit (increases equity).' },{ text: 'A credit in SOFP', correct: true, explanation: 'Correct! Profit credits equity.' },{ text: 'It doesn\'t transfer', correct: false, explanation: 'It must transfer to make SOFP balance.' },{ text: 'A debit in P&L', correct: false, explanation: 'The transfer is to SOFP, not back to P&L.' }] },
  { questionText: 'Opening inventory on the ETB appears in:', topic: 'Extended Trial Balance', difficulty: 'easy', syllabusRef: '5.6',
    aiExplanation: 'Opening inventory is a debit balance from the trial balance. It is transferred to the P&L columns as a debit (part of cost of sales). It does NOT appear in the SOFP columns — closing inventory replaces it there.',
    options: [{ text: 'SOFP debit column', correct: false, explanation: 'Closing inventory goes to SOFP, not opening.' },{ text: 'P&L debit column', correct: true, explanation: 'Correct! Part of cost of sales.' },{ text: 'Both P&L and SOFP', correct: false, explanation: 'Only closing inventory appears in both.' },{ text: 'Adjustment columns only', correct: false, explanation: 'It comes from the ledger balances.' }] },
  // --- Accounting Standards (6) ---
  { questionText: 'IAS 16 deals with:', topic: 'Accounting Standards (IAS)', difficulty: 'easy', syllabusRef: '6.1',
    aiExplanation: 'IAS 16 Property, Plant and Equipment sets out the accounting treatment for tangible non-current assets: recognition, measurement (cost model or revaluation model), depreciation, and disposal.',
    options: [{ text: 'Revenue recognition', correct: false, explanation: 'That is IFRS 15.' },{ text: 'Property, plant and equipment', correct: true, explanation: 'Correct!' },{ text: 'Inventories', correct: false, explanation: 'That is IAS 2.' },{ text: 'Leases', correct: false, explanation: 'That is IFRS 16.' }] },
  { questionText: 'Under IAS 2, inventory should be valued at:', topic: 'Accounting Standards (IAS)', difficulty: 'easy', syllabusRef: '6.2',
    aiExplanation: 'IAS 2 requires inventory at the lower of cost and net realisable value (NRV). Cost includes purchase price, conversion costs, and other costs to bring to current condition/location. NRV = estimated selling price less costs to complete and sell.',
    options: [{ text: 'Cost only', correct: false, explanation: 'Must compare with NRV.' },{ text: 'Lower of cost and NRV', correct: true, explanation: 'Correct!' },{ text: 'Market value', correct: false, explanation: 'NRV, not market value.' },{ text: 'Replacement cost', correct: false, explanation: 'Not under IAS 2.' }] },
  { questionText: 'The going concern assumption means:', topic: 'Accounting Standards (IAS)', difficulty: 'easy', syllabusRef: '6.3',
    aiExplanation: 'Going concern assumes the business will continue operating for the foreseeable future (at least 12 months). This justifies recording assets at cost (rather than liquidation value) and classifying liabilities as current/non-current.',
    options: [{ text: 'The business will continue operating for the foreseeable future', correct: true, explanation: 'Correct!' },{ text: 'The business is about to close', correct: false, explanation: 'That is the opposite — a going concern issue.' },{ text: 'Profits will increase next year', correct: false, explanation: 'Going concern is about survival, not profitability.' },{ text: 'All debts will be paid', correct: false, explanation: 'Not directly about debt payment.' }] },
  { questionText: 'The consistency concept requires that:', topic: 'Accounting Standards (IAS)', difficulty: 'easy', syllabusRef: '6.4',
    aiExplanation: 'Consistency requires the same accounting methods to be applied from period to period. This allows meaningful comparison of financial statements over time. Changes are permitted only if they provide more relevant information.',
    options: [{ text: 'Different methods are used each year', correct: false, explanation: 'The opposite.' },{ text: 'The same accounting methods are applied consistently', correct: true, explanation: 'Correct!' },{ text: 'All businesses use the same methods', correct: false, explanation: 'Consistency is within a business, not across businesses.' },{ text: 'Revenue is always recognised on receipt', correct: false, explanation: 'That relates to revenue recognition.' }] },
  { questionText: 'Capital expenditure is:', topic: 'Accounting Standards (IAS)', difficulty: 'easy', syllabusRef: '6.5',
    aiExplanation: 'Capital expenditure is spending on non-current assets (items with long-term benefit). It is capitalised on the SOFP, not expensed in P&L. Revenue expenditure is day-to-day expenses charged to P&L.',
    options: [{ text: 'Day-to-day running expenses', correct: false, explanation: 'That is revenue expenditure.' },{ text: 'Spending on non-current assets', correct: true, explanation: 'Correct!' },{ text: 'All spending over £1,000', correct: false, explanation: 'Classification is by nature, not amount.' },{ text: 'Repairs to existing assets', correct: false, explanation: 'Repairs are revenue expenditure (unless they enhance the asset).' }] },
  { questionText: 'Which is revenue expenditure?', topic: 'Accounting Standards (IAS)', difficulty: 'easy', syllabusRef: '6.6',
    aiExplanation: 'Revenue expenditure is spending that benefits only the current period (day-to-day expenses). Examples: wages, rent, repairs, electricity. Capital expenditure benefits multiple periods (non-current assets).',
    options: [{ text: 'Buying a new delivery van', correct: false, explanation: 'Capital expenditure.' },{ text: 'Extending a factory building', correct: false, explanation: 'Capital expenditure (enhances the asset).' },{ text: 'Annual service of the delivery van', correct: true, explanation: 'Correct! Maintenance = revenue expenditure.' },{ text: 'Installing a new computer network', correct: false, explanation: 'Capital expenditure.' }] },
];

async function main() {
  console.log('\n🎓 Seeding L3 AVBK...\n');
  await seedModule('AVBK', AVBK);
  console.log('\n✅ Done!');
}
main().catch(console.error).finally(() => prisma.$disconnect());
