/**
 * Level 3 IDRX — Indirect Tax / VAT (40 questions)
 * Run: npx tsx prisma/seed-questions-l3-idrx.ts
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
interface QS { questionText: string; topic: string; difficulty: 'easy'|'medium'|'hard'; syllabusRef: string; aiExplanation: string; options: { text: string; correct: boolean; explanation: string }[]; }
async function seedModule(code: string, questions: QS[]) {
  const mod = await (prisma as any).examModule.findFirst({ where: { code } });
  if (!mod) { console.log(`  ⚠️ ${code} not found`); return; }
  const existing = await (prisma as any).question.count({ where: { moduleId: mod.id } });
  let added = 0;
  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const dup = await (prisma as any).question.findFirst({ where: { moduleId: mod.id, questionText: q.questionText } });
    if (dup) continue;
    const created = await (prisma as any).question.create({
      data: { moduleId: mod.id, questionText: q.questionText, topic: q.topic, difficulty: q.difficulty, syllabusRef: q.syllabusRef, aiExplanation: q.aiExplanation, sortOrder: existing + i + 1 },
    });
    for (let j = 0; j < q.options.length; j++) {
      await (prisma as any).questionOption.create({
        data: { questionId: created.id, optionText: q.options[j].text, isCorrect: q.options[j].correct, explanation: q.options[j].explanation, sortOrder: j + 1 },
      });
    }
    added++;
  }
  console.log(`  ✅ ${code}: ${added} new (${existing} existed)`);
}

const IDRX: QS[] = [
  // --- VAT Registration & Deregistration (8) ---
  { questionText: 'A business must register for VAT when taxable turnover exceeds the threshold in any rolling:', topic: 'VAT Registration & Deregistration', difficulty: 'easy', syllabusRef: '1.1',
    aiExplanation: 'Compulsory VAT registration is required when taxable turnover exceeds the threshold (£90,000 from April 2024) in the past 12 months (rolling), or if expected to exceed it in the next 30 days alone.',
    options: [{ text: '12-month period', correct: true, explanation: 'Correct! Rolling 12 months.' },{ text: '6-month period', correct: false, explanation: 'The test is 12 months, not 6.' },{ text: 'Calendar year', correct: false, explanation: 'Rolling 12 months, not calendar year.' },{ text: '3-month period', correct: false, explanation: 'Too short a period.' }] },
  { questionText: 'The current UK VAT registration threshold (2024/25) is:', topic: 'VAT Registration & Deregistration', difficulty: 'easy', syllabusRef: '1.2',
    aiExplanation: 'From April 2024, the VAT registration threshold is £90,000. The deregistration threshold is £88,000.',
    options: [{ text: '£85,000', correct: false, explanation: 'Previous threshold.' },{ text: '£90,000', correct: true, explanation: 'Correct! From April 2024.' },{ text: '£100,000', correct: false, explanation: 'Too high.' },{ text: '£50,000', correct: false, explanation: 'Too low.' }] },
  { questionText: 'Voluntary VAT registration is beneficial when:', topic: 'VAT Registration & Deregistration', difficulty: 'medium', syllabusRef: '1.3',
    aiExplanation: 'Voluntary registration lets businesses below the threshold reclaim input VAT. Beneficial when: most customers are VAT-registered (they can reclaim the VAT you charge), significant input VAT on purchases, wanting to appear more professional/established.',
    options: [{ text: 'The business only sells to VAT-exempt customers', correct: false, explanation: 'Charging VAT to exempt customers would increase their costs.' },{ text: 'The business has significant input VAT to reclaim', correct: true, explanation: 'Correct!' },{ text: 'The business wants to avoid all tax', correct: false, explanation: 'VAT registration does not avoid tax.' },{ text: 'The business sells only zero-rated goods', correct: false, explanation: 'This IS a benefit — can reclaim input with no output. So this is partially correct but the better answer is significant input VAT.' }] },
  { questionText: 'A business can deregister for VAT if taxable turnover falls below:', topic: 'VAT Registration & Deregistration', difficulty: 'easy', syllabusRef: '1.4',
    aiExplanation: 'The VAT deregistration threshold is £88,000 (2024/25). If taxable turnover is expected to fall below this in the next 12 months, the business can apply to deregister.',
    options: [{ text: '£88,000', correct: true, explanation: 'Correct!' },{ text: '£90,000', correct: false, explanation: 'That is the registration threshold.' },{ text: '£85,000', correct: false, explanation: 'Previous deregistration threshold.' },{ text: '£50,000', correct: false, explanation: 'Too low.' }] },
  { questionText: 'Once registered, a business must notify HMRC within how many days of the end of the month when the threshold is exceeded?', topic: 'VAT Registration & Deregistration', difficulty: 'medium', syllabusRef: '1.5',
    aiExplanation: 'A business must notify HMRC within 30 days of the end of the month in which the threshold was exceeded. Registration is then effective from the first day of the second month after exceeding the threshold.',
    options: [{ text: '30 days', correct: true, explanation: 'Correct!' },{ text: '14 days', correct: false, explanation: 'Too short.' },{ text: '90 days', correct: false, explanation: 'Too long.' },{ text: '7 days', correct: false, explanation: 'Too short.' }] },
  { questionText: 'Exempt supplies are:', topic: 'Standard-Rated, Zero-Rated, Exempt Supplies', difficulty: 'easy', syllabusRef: '2.1',
    aiExplanation: 'Exempt supplies are outside the VAT system. No VAT is charged and input VAT on related costs CANNOT be reclaimed. Examples: insurance, financial services, education, health services, burial/cremation.',
    options: [{ text: 'Charged at 0% VAT with input VAT reclaimable', correct: false, explanation: 'That is zero-rated.' },{ text: 'Outside the VAT system — no VAT charged, input VAT NOT reclaimable', correct: true, explanation: 'Correct!' },{ text: 'Charged at 20% VAT', correct: false, explanation: 'That is standard-rated.' },{ text: 'The same as zero-rated', correct: false, explanation: 'Key difference: exempt cannot reclaim input VAT.' }] },
  { questionText: 'Which of these is zero-rated for VAT?', topic: 'Standard-Rated, Zero-Rated, Exempt Supplies', difficulty: 'easy', syllabusRef: '2.2',
    aiExplanation: 'Zero-rated items: most food (not restaurant meals), children\'s clothing, books/newspapers, public transport, new residential buildings, prescription drugs.',
    options: [{ text: 'Restaurant meals', correct: false, explanation: 'Standard-rated at 20%.' },{ text: 'Children\'s clothing', correct: true, explanation: 'Correct!' },{ text: 'Alcohol', correct: false, explanation: 'Standard-rated.' },{ text: 'Electricity for business', correct: false, explanation: 'Reduced rate (5%) for domestic, standard for business.' }] },
  { questionText: 'The reduced rate of VAT (5%) applies to:', topic: 'Standard-Rated, Zero-Rated, Exempt Supplies', difficulty: 'medium', syllabusRef: '2.3',
    aiExplanation: 'The UK reduced rate of 5% applies to: domestic fuel and power (gas, electricity), children\'s car seats, smoking cessation products, installation of energy-saving materials, and some mobility aids.',
    options: [{ text: 'All food', correct: false, explanation: 'Most food is zero-rated.' },{ text: 'Domestic fuel and power', correct: true, explanation: 'Correct!' },{ text: 'Adult clothing', correct: false, explanation: 'Standard-rated.' },{ text: 'Professional services', correct: false, explanation: 'Standard-rated.' }] },
  // --- Input & Output VAT (8) ---
  { questionText: 'A business sells goods for £2,000 plus VAT at 20% and buys goods for £800 plus VAT. Net VAT payable?', topic: 'Input & Output VAT', difficulty: 'easy', syllabusRef: '3.1',
    aiExplanation: 'Output VAT = 20% × £2,000 = £400. Input VAT = 20% × £800 = £160. Net payable = £400 - £160 = £240 to HMRC.',
    options: [{ text: '£240', correct: true, explanation: 'Correct! £400 output - £160 input.' },{ text: '£400', correct: false, explanation: 'Must deduct input VAT.' },{ text: '£160', correct: false, explanation: 'That is input VAT only.' },{ text: '£560', correct: false, explanation: 'Added both instead of netting.' }] },
  { questionText: 'Input VAT on entertaining UK customers is:', topic: 'Input & Output VAT', difficulty: 'medium', syllabusRef: '3.2',
    aiExplanation: 'Input VAT on business entertainment of UK customers is NOT reclaimable (blocked input tax). However, staff entertainment (e.g., Christmas party) IS reclaimable, and entertaining overseas customers IS reclaimable.',
    options: [{ text: 'Fully reclaimable', correct: false, explanation: 'Business entertainment VAT is blocked.' },{ text: 'Not reclaimable', correct: true, explanation: 'Correct! Blocked input tax.' },{ text: 'Reclaimable at 50%', correct: false, explanation: 'No partial reclaim — fully blocked.' },{ text: 'Reclaimable if over £25', correct: false, explanation: 'No amount threshold applies.' }] },
  { questionText: 'A VAT-registered business buys a car for £20,000 plus VAT for a sales director. Can input VAT be reclaimed?', topic: 'Input & Output VAT', difficulty: 'hard', syllabusRef: '3.3',
    aiExplanation: 'Input VAT on cars is generally NOT reclaimable if there is any private use. Since a sales director\'s car typically has private use, the £4,000 input VAT cannot be reclaimed. Exception: 100% business use cars (e.g., pool cars, driving school cars, taxis) CAN reclaim.',
    options: [{ text: 'Yes — full £4,000', correct: false, explanation: 'Private use = no reclaim on cars.' },{ text: 'No — blocked because of private use', correct: true, explanation: 'Correct!' },{ text: 'Yes — 50% = £2,000', correct: false, explanation: 'No 50% rule for cars — fully blocked or fully reclaimable.' },{ text: 'Only if the car costs under £25,000', correct: false, explanation: 'No cost threshold.' }] },
  { questionText: 'A business receives a pro-forma invoice. Can it reclaim input VAT on it?', topic: 'Input & Output VAT', difficulty: 'medium', syllabusRef: '3.4',
    aiExplanation: 'A pro-forma invoice is NOT a valid VAT invoice — it is a request for payment before goods are sent. Input VAT can ONLY be reclaimed on a valid VAT invoice (or simplified invoice for amounts under £250).',
    options: [{ text: 'Yes — any invoice qualifies', correct: false, explanation: 'Must be a valid VAT invoice.' },{ text: 'No — a pro-forma is not a valid VAT invoice', correct: true, explanation: 'Correct!' },{ text: 'Yes — if the amount exceeds £250', correct: false, explanation: 'Amount is irrelevant — pro-formas never qualify.' },{ text: 'Only if the supplier is VAT-registered', correct: false, explanation: 'Even from VAT-registered suppliers, pro-formas don\'t count.' }] },
  { questionText: 'A valid VAT invoice must include the supplier\'s VAT registration number. What other detail is required?', topic: 'Input & Output VAT', difficulty: 'medium', syllabusRef: '3.5',
    aiExplanation: 'Full VAT invoice requirements: supplier name/address, VAT reg number, invoice date, unique invoice number, customer name/address, description of goods/services, quantity, unit price, VAT rate, total excluding VAT, total VAT, total including VAT.',
    options: [{ text: 'Supplier\'s bank sort code', correct: false, explanation: 'Not a VAT requirement.' },{ text: 'Unique sequential invoice number', correct: true, explanation: 'Correct!' },{ text: 'Customer\'s NI number', correct: false, explanation: 'Not required.' },{ text: 'Supplier\'s corporation tax reference', correct: false, explanation: 'Not required.' }] },
  { questionText: 'The tax point for a supply of goods is generally:', topic: 'Input & Output VAT', difficulty: 'medium', syllabusRef: '3.6',
    aiExplanation: 'The basic tax point for goods is the date of delivery or removal. For services, it is when the service is performed. An actual tax point can override this: if an invoice is issued or payment received within 14 days before the basic tax point.',
    options: [{ text: 'The date of delivery', correct: true, explanation: 'Correct! Basic tax point for goods.' },{ text: 'The date of the invoice', correct: false, explanation: 'Invoice date can create an actual tax point, but basic is delivery.' },{ text: 'The date of payment', correct: false, explanation: 'Unless using cash accounting scheme.' },{ text: 'The end of the VAT quarter', correct: false, explanation: 'Not related to quarter end.' }] },
  { questionText: 'A simplified VAT invoice can be used for supplies up to:', topic: 'Input & Output VAT', difficulty: 'easy', syllabusRef: '3.7',
    aiExplanation: 'A simplified (or less detailed) VAT invoice can be issued for supplies of £250 or less (including VAT). It needs fewer details: supplier name/address/VAT number, date, description, total including VAT, and VAT rate.',
    options: [{ text: '£250 including VAT', correct: true, explanation: 'Correct!' },{ text: '£100 including VAT', correct: false, explanation: 'Too low.' },{ text: '£1,000 including VAT', correct: false, explanation: 'Too high.' },{ text: '£500 excluding VAT', correct: false, explanation: 'Wrong amount and basis.' }] },
  { questionText: 'Output VAT is the VAT:', topic: 'Input & Output VAT', difficulty: 'easy', syllabusRef: '3.8',
    aiExplanation: 'Output VAT is charged on sales (outputs) to customers. It is collected by the business on behalf of HMRC. Input VAT is paid on purchases (inputs) from suppliers and can usually be reclaimed.',
    options: [{ text: 'Paid on purchases from suppliers', correct: false, explanation: 'That is input VAT.' },{ text: 'Charged on sales to customers', correct: true, explanation: 'Correct!' },{ text: 'Paid to HMRC quarterly', correct: false, explanation: 'The NET amount (output - input) is paid.' },{ text: 'Only on exports', correct: false, explanation: 'On all taxable supplies, not just exports.' }] },
  // --- VAT Return (8) ---
  { questionText: 'How often must a standard VAT return be submitted?', topic: 'VAT Return (Box 1-9)', difficulty: 'easy', syllabusRef: '4.1',
    aiExplanation: 'Standard VAT returns are submitted quarterly (every 3 months). The return and payment are due 1 month and 7 days after the end of the VAT period (for online filing).',
    options: [{ text: 'Monthly', correct: false, explanation: 'Monthly returns are optional for large businesses.' },{ text: 'Quarterly', correct: true, explanation: 'Correct!' },{ text: 'Annually', correct: false, explanation: 'Annual accounting scheme exists but standard is quarterly.' },{ text: 'Every 6 months', correct: false, explanation: 'Not a standard period.' }] },
  { questionText: 'VAT return Box 1 shows:', topic: 'VAT Return (Box 1-9)', difficulty: 'easy', syllabusRef: '4.2',
    aiExplanation: 'Box 1: VAT due on sales and other outputs. Box 2: VAT due on EU acquisitions. Box 3: Total VAT due (Box 1 + Box 2). Box 4: VAT reclaimed on inputs. Box 5: Net VAT (Box 3 - Box 4). Box 6: Total sales ex-VAT. Box 7: Total purchases ex-VAT.',
    options: [{ text: 'VAT due on sales (output VAT)', correct: true, explanation: 'Correct!' },{ text: 'VAT reclaimed on purchases', correct: false, explanation: 'That is Box 4.' },{ text: 'Net VAT payable', correct: false, explanation: 'That is Box 5.' },{ text: 'Total value of sales', correct: false, explanation: 'That is Box 6.' }] },
  { questionText: 'Box 5 of the VAT return shows:', topic: 'VAT Return (Box 1-9)', difficulty: 'easy', syllabusRef: '4.3',
    aiExplanation: 'Box 5 = Box 3 (total output) - Box 4 (total input). If positive, the business owes HMRC. If negative, HMRC owes the business a refund.',
    options: [{ text: 'Total output VAT', correct: false, explanation: 'That is Box 3.' },{ text: 'Net VAT payable or reclaimable', correct: true, explanation: 'Correct!' },{ text: 'Total sales excluding VAT', correct: false, explanation: 'That is Box 6.' },{ text: 'Total input VAT', correct: false, explanation: 'That is Box 4.' }] },
  { questionText: 'Boxes 6 and 7 of the VAT return show amounts:', topic: 'VAT Return (Box 1-9)', difficulty: 'medium', syllabusRef: '4.4',
    aiExplanation: 'Box 6: total value of sales excluding VAT (includes zero-rated and exempt). Box 7: total value of purchases excluding VAT. Both are rounded to whole pounds.',
    options: [{ text: 'Including VAT', correct: false, explanation: 'Excluding VAT.' },{ text: 'Excluding VAT', correct: true, explanation: 'Correct!' },{ text: 'Of VAT only', correct: false, explanation: 'They show the net values.' },{ text: 'For standard-rated supplies only', correct: false, explanation: 'All supplies including zero-rated and exempt.' }] },
  { questionText: 'The deadline for online VAT return filing and payment is:', topic: 'VAT Return (Box 1-9)', difficulty: 'medium', syllabusRef: '4.5',
    aiExplanation: '1 calendar month + 7 days after the end of the VAT period. E.g., for quarter ending 31 March, deadline is 7 May. Making Tax Digital requires online filing.',
    options: [{ text: '1 month and 7 days after the period end', correct: true, explanation: 'Correct!' },{ text: '14 days after the period end', correct: false, explanation: 'Too short.' },{ text: '3 months after the period end', correct: false, explanation: 'Too long.' },{ text: 'The last day of the following month', correct: false, explanation: 'Close but misses the 7 extra days for online.' }] },
  { questionText: 'A business with a VAT quarter ending 30 June must file and pay by:', topic: 'VAT Return (Box 1-9)', difficulty: 'medium', syllabusRef: '4.6',
    aiExplanation: '30 June + 1 month = 31 July + 7 days = 7 August. So the deadline is 7 August.',
    options: [{ text: '7 August', correct: true, explanation: 'Correct! 1 month + 7 days.' },{ text: '31 July', correct: false, explanation: 'Missing the 7 extra days.' },{ text: '7 July', correct: false, explanation: 'Only 7 days, not 1 month + 7.' },{ text: '30 September', correct: false, explanation: 'Far too late.' }] },
  { questionText: 'What happens if a VAT return is submitted late?', topic: 'VAT Penalties & Surcharges', difficulty: 'medium', syllabusRef: '5.1',
    aiExplanation: 'Under the new penalty regime (from Jan 2023): Late submission incurs penalty points. Once a threshold is reached, a £200 penalty applies for each further late submission. Late payment incurs a percentage penalty on the outstanding VAT.',
    options: [{ text: 'Nothing — there are no penalties', correct: false, explanation: 'Penalties DO apply.' },{ text: 'Penalty points leading to £200 penalties', correct: true, explanation: 'Correct! Points-based system.' },{ text: 'Automatic deregistration', correct: false, explanation: 'Not automatic deregistration.' },{ text: '50% surcharge on the VAT owed', correct: false, explanation: 'Old surcharge system replaced in 2023.' }] },
  { questionText: 'Interest on late VAT payments runs from:', topic: 'VAT Penalties & Surcharges', difficulty: 'hard', syllabusRef: '5.2',
    aiExplanation: 'Under the new regime, late payment interest runs from the day after the payment due date until the date of payment. The rate is Bank of England base rate + 2.5%.',
    options: [{ text: 'The day after the payment due date', correct: true, explanation: 'Correct!' },{ text: 'The end of the VAT quarter', correct: false, explanation: 'Runs from the due date, not period end.' },{ text: '30 days after the due date', correct: false, explanation: 'No grace period for interest.' },{ text: 'Interest is not charged on VAT', correct: false, explanation: 'Interest IS charged on late VAT.' }] },
  // --- VAT Schemes (8) ---
  { questionText: 'The flat rate scheme allows a business to:', topic: 'Flat Rate Scheme', difficulty: 'easy', syllabusRef: '6.1',
    aiExplanation: 'The flat rate scheme simplifies VAT by applying a fixed percentage to gross (VAT-inclusive) turnover. The business keeps the difference between the VAT charged to customers and the flat rate amount paid to HMRC. No input VAT is reclaimed (except on capital goods over £2,000).',
    options: [{ text: 'Pay a fixed percentage of turnover instead of calculating VAT on each transaction', correct: true, explanation: 'Correct!' },{ text: 'Avoid charging VAT to customers', correct: false, explanation: 'Must still charge 20% VAT.' },{ text: 'Reclaim all input VAT', correct: false, explanation: 'Cannot reclaim input VAT (except capital goods >£2,000).' },{ text: 'File VAT returns annually', correct: false, explanation: 'That is the annual accounting scheme.' }] },
  { questionText: 'The flat rate scheme is available to businesses with taxable turnover up to:', topic: 'Flat Rate Scheme', difficulty: 'easy', syllabusRef: '6.2',
    aiExplanation: 'The flat rate scheme is available to businesses with expected taxable turnover of £150,000 or less (excluding VAT) in the next 12 months. Must leave if turnover exceeds £230,000.',
    options: [{ text: '£150,000', correct: true, explanation: 'Correct! Entry threshold.' },{ text: '£90,000', correct: false, explanation: 'That is the VAT registration threshold.' },{ text: '£85,000', correct: false, explanation: 'Previous registration threshold.' },{ text: '£1,000,000', correct: false, explanation: 'Far too high.' }] },
  { questionText: 'Under the cash accounting scheme, output VAT is accounted for when:', topic: 'Cash Accounting Scheme', difficulty: 'easy', syllabusRef: '7.1',
    aiExplanation: 'Under cash accounting, VAT is accounted for based on cash received and paid, not invoice dates. Output VAT is due when payment is RECEIVED from customers. Input VAT is reclaimed when payment is MADE to suppliers.',
    options: [{ text: 'The invoice is issued', correct: false, explanation: 'That is the standard (accruals) basis.' },{ text: 'Payment is received from the customer', correct: true, explanation: 'Correct! Cash basis.' },{ text: 'Goods are delivered', correct: false, explanation: 'That is the basic tax point.' },{ text: 'The VAT return is filed', correct: false, explanation: 'Not related to filing date.' }] },
  { questionText: 'The main advantage of the cash accounting scheme is:', topic: 'Cash Accounting Scheme', difficulty: 'medium', syllabusRef: '7.2',
    aiExplanation: 'Main advantage: no output VAT is paid until the customer pays. This helps cash flow — the business doesn\'t have to pay HMRC before receiving the money. Also provides automatic bad debt relief (if the customer never pays, no output VAT is due).',
    options: [{ text: 'Simplified record-keeping', correct: false, explanation: 'That is the flat rate scheme benefit.' },{ text: 'No output VAT until customer pays — helping cash flow', correct: true, explanation: 'Correct!' },{ text: 'Lower VAT rates', correct: false, explanation: 'Same rates apply.' },{ text: 'No need to register for VAT', correct: false, explanation: 'Must be VAT-registered.' }] },
  { questionText: 'The annual accounting scheme allows:', topic: 'Cash Accounting Scheme', difficulty: 'easy', syllabusRef: '7.3',
    aiExplanation: 'Annual accounting: one VAT return per year (instead of quarterly), with interim payments (monthly or quarterly). The balancing payment is made with the annual return. Available for businesses under £1.35m turnover.',
    options: [{ text: 'One VAT return per year with interim payments', correct: true, explanation: 'Correct!' },{ text: 'No VAT payments at all during the year', correct: false, explanation: 'Interim payments are required.' },{ text: 'Quarterly returns with annual payment', correct: false, explanation: 'One annual return, not quarterly.' },{ text: 'Exemption from Making Tax Digital', correct: false, explanation: 'MTD still applies.' }] },
  { questionText: 'Under Making Tax Digital (MTD), VAT records must be kept:', topic: 'Making Tax Digital (MTD)', difficulty: 'easy', syllabusRef: '8.1',
    aiExplanation: 'MTD requires VAT-registered businesses to keep digital records and submit VAT returns using compatible software. Manual records and spreadsheet submissions to HMRC portal are no longer accepted.',
    options: [{ text: 'On paper only', correct: false, explanation: 'MTD requires digital records.' },{ text: 'Digitally using compatible software', correct: true, explanation: 'Correct!' },{ text: 'In any format the business chooses', correct: false, explanation: 'Must be digital and MTD-compatible.' },{ text: 'Only by an accountant', correct: false, explanation: 'Business can do it themselves with compatible software.' }] },
  { questionText: 'Bad debt relief for VAT purposes can be claimed when a debt is:', topic: 'VAT Penalties & Surcharges', difficulty: 'medium', syllabusRef: '5.3',
    aiExplanation: 'VAT bad debt relief can be claimed when: (1) the debt is at least 6 months old from the later of the due date or supply date, (2) the debt has been written off in the accounts, (3) the output VAT was paid to HMRC. The business can reclaim the output VAT previously paid.',
    options: [{ text: 'At least 6 months overdue and written off', correct: true, explanation: 'Correct!' },{ text: 'At least 30 days overdue', correct: false, explanation: 'Too short — must be 6 months.' },{ text: 'At least 12 months overdue', correct: false, explanation: 'Only 6 months required.' },{ text: 'Any overdue debt regardless of age', correct: false, explanation: 'Must be at least 6 months old.' }] },
  { questionText: 'A business using the flat rate scheme has a flat rate percentage of 14.5%. Gross sales (incl VAT) are £48,000. VAT payable to HMRC?', topic: 'Flat Rate Scheme', difficulty: 'medium', syllabusRef: '6.3',
    aiExplanation: 'Flat rate VAT = Flat rate % × Gross turnover = 14.5% × £48,000 = £6,960. The business charged £8,000 output VAT (£48,000 × 20/120) but only pays £6,960 — keeping £1,040.',
    options: [{ text: '£6,960', correct: true, explanation: 'Correct! 14.5% × £48,000.' },{ text: '£8,000', correct: false, explanation: 'That would be the standard 20/120 calc.' },{ text: '£5,800', correct: false, explanation: 'Incorrect percentage applied.' },{ text: '£9,600', correct: false, explanation: 'Used 20% instead of 14.5%.' }] },
  // --- Additional (8) ---
  { questionText: 'Partial exemption applies when a business makes:', topic: 'Standard-Rated, Zero-Rated, Exempt Supplies', difficulty: 'hard', syllabusRef: '2.4',
    aiExplanation: 'Partial exemption applies when a business makes both taxable (standard/zero-rated) AND exempt supplies. Input VAT must be apportioned: VAT on taxable supplies is reclaimable, VAT on exempt supplies is not, and residual (mixed) VAT is apportioned using the standard method or a special method.',
    options: [{ text: 'Only standard-rated supplies', correct: false, explanation: 'No partial exemption needed if all taxable.' },{ text: 'Both taxable and exempt supplies', correct: true, explanation: 'Correct!' },{ text: 'Only exempt supplies', correct: false, explanation: 'If all exempt, no VAT to apportion.' },{ text: 'Only zero-rated supplies', correct: false, explanation: 'Zero-rated = taxable, so no partial exemption.' }] },
  { questionText: 'A credit note for £120 including VAT at 20% reduces output VAT by:', topic: 'Input & Output VAT', difficulty: 'easy', syllabusRef: '3.9',
    aiExplanation: 'VAT in £120 gross = £120 × 20/120 = £20. The credit note reduces output VAT by £20.',
    options: [{ text: '£20', correct: true, explanation: 'Correct! £120 × 20/120.' },{ text: '£24', correct: false, explanation: '20% of £120 = £24 is wrong — must use the VAT fraction.' },{ text: '£100', correct: false, explanation: 'That is the net amount.' },{ text: '£120', correct: false, explanation: 'That is the gross amount.' }] },
  { questionText: 'EU imports since Brexit are treated for VAT as:', topic: 'Input & Output VAT', difficulty: 'medium', syllabusRef: '3.10',
    aiExplanation: 'Since 1 January 2021 (Brexit), EU imports are treated the same as imports from the rest of the world. Import VAT is due at the point of import. Postponed VAT accounting allows businesses to account for import VAT on their VAT return instead of paying at the border.',
    options: [{ text: 'EU acquisitions with reverse charge', correct: false, explanation: 'Pre-Brexit treatment.' },{ text: 'Imports — same as non-EU, with import VAT', correct: true, explanation: 'Correct!' },{ text: 'Zero-rated', correct: false, explanation: 'Imports are taxable.' },{ text: 'Exempt', correct: false, explanation: 'Imports are subject to VAT.' }] },
  { questionText: 'The reverse charge mechanism means:', topic: 'Input & Output VAT', difficulty: 'hard', syllabusRef: '3.11',
    aiExplanation: 'Under the reverse charge, the customer (not the supplier) accounts for the VAT. The customer charges themselves output VAT and simultaneously reclaims it as input VAT (if fully taxable). Used for certain services from overseas suppliers and in construction (CIS).',
    options: [{ text: 'The customer accounts for VAT instead of the supplier', correct: true, explanation: 'Correct!' },{ text: 'The supplier gets a refund of VAT', correct: false, explanation: 'The supplier doesn\'t charge VAT at all.' },{ text: 'VAT is charged at a reduced rate', correct: false, explanation: 'Same rate, different accounting mechanism.' },{ text: 'No VAT is due on the transaction', correct: false, explanation: 'VAT is due — just accounted for by the customer.' }] },
  { questionText: 'Fuel scale charges apply when:', topic: 'Input & Output VAT', difficulty: 'medium', syllabusRef: '3.12',
    aiExplanation: 'If a business reclaims all input VAT on fuel (including private use), it must pay a fuel scale charge. This is a fixed amount based on CO2 emissions that accounts for the private use element. The alternative is to only reclaim the business proportion of fuel VAT.',
    options: [{ text: 'A business reclaims all fuel VAT but some fuel is used privately', correct: true, explanation: 'Correct!' },{ text: 'A business buys electric vehicles', correct: false, explanation: 'Not related to EVs.' },{ text: 'Fuel prices exceed a threshold', correct: false, explanation: 'Based on private use, not fuel price.' },{ text: 'A business uses the flat rate scheme', correct: false, explanation: 'Flat rate already simplifies VAT.' }] },
  { questionText: 'The de minimis limit for partial exemption means:', topic: 'Standard-Rated, Zero-Rated, Exempt Supplies', difficulty: 'hard', syllabusRef: '2.5',
    aiExplanation: 'De minimis: if exempt input VAT is below £625/month on average AND below 50% of total input VAT, the business can treat it as fully reclaimable. This simplifies VAT for businesses with small amounts of exempt supplies.',
    options: [{ text: 'All exempt input VAT can be reclaimed if below certain limits', correct: true, explanation: 'Correct! Below £625/month average AND <50% of total input.' },{ text: 'No input VAT can ever be reclaimed', correct: false, explanation: 'De minimis allows full reclaim.' },{ text: 'The business must deregister', correct: false, explanation: 'Not about deregistration.' },{ text: 'Only capital goods VAT is affected', correct: false, explanation: 'Applies to all input VAT.' }] },
  { questionText: 'A tax invoice must be issued within how many days of the tax point?', topic: 'Input & Output VAT', difficulty: 'easy', syllabusRef: '3.13',
    aiExplanation: 'A VAT invoice must be issued within 30 days of the tax point (date of supply). If issued within 14 days before the basic tax point, it creates an actual tax point on the invoice date.',
    options: [{ text: '30 days', correct: true, explanation: 'Correct!' },{ text: '14 days', correct: false, explanation: '14 days is for the actual tax point rule.' },{ text: '7 days', correct: false, explanation: 'Too short.' },{ text: '90 days', correct: false, explanation: 'Too long.' }] },
  { questionText: 'Which VAT scheme is best for businesses wanting fewer returns?', topic: 'Cash Accounting Scheme', difficulty: 'easy', syllabusRef: '7.4',
    aiExplanation: 'The annual accounting scheme reduces returns from 4 per year to 1, with interim payments. The flat rate scheme simplifies calculation but still requires quarterly returns. Cash accounting changes WHEN VAT is due, not frequency.',
    options: [{ text: 'Cash accounting scheme', correct: false, explanation: 'Still quarterly returns.' },{ text: 'Flat rate scheme', correct: false, explanation: 'Still quarterly returns.' },{ text: 'Annual accounting scheme', correct: true, explanation: 'Correct! One return per year.' },{ text: 'Standard scheme', correct: false, explanation: 'Quarterly returns.' }] },
];

async function main() {
  console.log('\n🎓 Seeding L3 IDRX...\n');
  await seedModule('IDRX', IDRX);
  console.log('\n✅ Done!');
}
main().catch(console.error).finally(() => prisma.$disconnect());
