/**
 * Level 4 FASL — Drafting and Interpreting Financial Statements (40 questions)
 * Run: npx tsx prisma/seed-questions-l4-fasl.ts
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
interface QS { questionText: string; topic: string; difficulty: 'easy'|'medium'|'hard'; syllabusRef: string; aiExplanation: string; options: { text: string; correct: boolean; explanation: string }[]; }
async function seedModule(code: string, questions: QS[]) {
  const mod = await (prisma as any).examModule.findFirst({ where: { code } });
  if (!mod) { console.log(`  ⚠️ ${code} not found`); return; }
  const existing = await (prisma as any).question.count({ where: { moduleId: mod.id } });
  let added = 0;
  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const dup = await (prisma as any).question.findFirst({ where: { moduleId: mod.id, questionText: q.questionText } });
    if (dup) continue;
    const created = await (prisma as any).question.create({
      data: { moduleId: mod.id, questionText: q.questionText, topic: q.topic, difficulty: q.difficulty, syllabusRef: q.syllabusRef, aiExplanation: q.aiExplanation, sortOrder: existing + i + 1 },
    });
    for (let j = 0; j < q.options.length; j++) {
      await (prisma as any).questionOption.create({
        data: { questionId: created.id, optionText: q.options[j].text, isCorrect: q.options[j].correct, explanation: q.options[j].explanation, sortOrder: j + 1 },
      });
    }
    added++;
  }
  console.log(`  ✅ ${code}: ${added} new (${existing} existed)`);
}

const FASL: QS[] = [
  // --- Limited Company Accounts (8) ---
  { questionText: 'The main difference between a sole trader\'s and a limited company\'s financial statements is:', topic: 'Limited Company Accounts', difficulty: 'easy', syllabusRef: '1.1',
    aiExplanation: 'Limited companies are separate legal entities — they have shareholders\' equity (share capital + reserves) instead of owner\'s capital. They must comply with Companies Act 2006 and IAS/IFRS. They produce: statement of profit or loss, statement of financial position, statement of changes in equity, statement of cash flows, and notes.',
    options: [{ text: 'Limited companies have share capital and reserves instead of owner\'s capital', correct: true, explanation: 'Correct!' },{ text: 'Sole traders must follow IFRS', correct: false, explanation: 'Companies follow IFRS; sole traders follow FRS 102 or simpler standards.' },{ text: 'Limited companies don\'t need a balance sheet', correct: false, explanation: 'They must prepare one.' },{ text: 'There is no difference', correct: false, explanation: 'Significant structural differences.' }] },
  { questionText: 'Retained earnings on a company\'s SOFP represent:', topic: 'Limited Company Accounts', difficulty: 'easy', syllabusRef: '1.2',
    aiExplanation: 'Retained earnings are accumulated profits less accumulated losses and dividends. They represent profits that have been reinvested in the business rather than distributed to shareholders.',
    options: [{ text: 'Accumulated profits not yet distributed as dividends', correct: true, explanation: 'Correct!' },{ text: 'Cash held in the bank', correct: false, explanation: 'Retained earnings are not the same as cash.' },{ text: 'Share capital issued', correct: false, explanation: 'Share capital is separate.' },{ text: 'Total revenue for the year', correct: false, explanation: 'Revenue is a P&L item.' }] },
  { questionText: 'A company issues 100,000 ordinary shares of £1 each at £1.50. Share capital is:', topic: 'Limited Company Accounts', difficulty: 'medium', syllabusRef: '1.3',
    aiExplanation: 'Share capital = nominal value × number of shares = 100,000 × £1 = £100,000. Share premium = (issue price - nominal) × shares = (£1.50-£1) × 100,000 = £50,000. Total equity raised = £150,000.',
    options: [{ text: '£100,000', correct: true, explanation: 'Correct! 100,000 × £1 nominal.' },{ text: '£150,000', correct: false, explanation: 'That is total proceeds — share capital is at nominal value.' },{ text: '£50,000', correct: false, explanation: 'That is the share premium.' },{ text: '£1.50', correct: false, explanation: 'That is the price per share.' }] },
  { questionText: 'Share premium arises when shares are issued:', topic: 'Limited Company Accounts', difficulty: 'easy', syllabusRef: '1.4',
    aiExplanation: 'Share premium = amount received above the nominal (par) value of shares. It is a non-distributable reserve — it cannot be paid out as dividends. It forms part of shareholders\' equity.',
    options: [{ text: 'Below their nominal value', correct: false, explanation: 'Shares cannot be issued below nominal (at a discount) under UK law.' },{ text: 'Above their nominal value', correct: true, explanation: 'Correct!' },{ text: 'At exactly nominal value', correct: false, explanation: 'No premium if issued at par.' },{ text: 'To existing shareholders only', correct: false, explanation: 'Premium relates to price, not who buys.' }] },
  { questionText: 'Dividends proposed but not yet paid at year end are:', topic: 'Limited Company Accounts', difficulty: 'medium', syllabusRef: '1.5',
    aiExplanation: 'Under IAS 10, dividends proposed after the year end are NOT a liability at the year end (non-adjusting event). They are disclosed in the notes only. Dividends declared before the year end ARE a liability.',
    options: [{ text: 'Shown as a current liability', correct: false, explanation: 'Only if declared before year end.' },{ text: 'Disclosed in the notes but not a liability', correct: true, explanation: 'Correct! Per IAS 10.' },{ text: 'Deducted from revenue', correct: false, explanation: 'Dividends are not an expense.' },{ text: 'Added to share capital', correct: false, explanation: 'Dividends are distributions, not capital.' }] },
  { questionText: 'Corporation tax for the year appears on the SOFP as:', topic: 'Limited Company Accounts', difficulty: 'easy', syllabusRef: '1.6',
    aiExplanation: 'Corporation tax for the year is accrued as a current liability (tax payable). It is estimated at year end. The tax expense appears in the P&L, and the unpaid amount is a liability.',
    options: [{ text: 'A current liability', correct: true, explanation: 'Correct!' },{ text: 'A non-current liability', correct: false, explanation: 'Due within 9 months — current.' },{ text: 'A current asset', correct: false, explanation: 'It is owed, not receivable.' },{ text: 'Part of share capital', correct: false, explanation: 'Not related to capital.' }] },
  { questionText: 'The statement of changes in equity shows:', topic: 'Limited Company Accounts', difficulty: 'medium', syllabusRef: '1.7',
    aiExplanation: 'The statement of changes in equity reconciles opening and closing equity. It shows: profit/loss for the year, dividends paid, shares issued, revaluation gains/losses, and other comprehensive income items.',
    options: [{ text: 'Cash inflows and outflows', correct: false, explanation: 'That is the cash flow statement.' },{ text: 'Movements in equity from opening to closing balance', correct: true, explanation: 'Correct!' },{ text: 'Revenue and expenses only', correct: false, explanation: 'That is the P&L.' },{ text: 'Assets and liabilities', correct: false, explanation: 'That is the SOFP.' }] },
  { questionText: 'Which reserve is distributable (can be paid as dividends)?', topic: 'Limited Company Accounts', difficulty: 'medium', syllabusRef: '1.8',
    aiExplanation: 'Distributable reserves: retained earnings. Non-distributable: share premium, revaluation reserve, capital redemption reserve. Only accumulated realised profits (less realised losses) can be distributed.',
    options: [{ text: 'Share premium', correct: false, explanation: 'Non-distributable.' },{ text: 'Revaluation reserve', correct: false, explanation: 'Non-distributable (unrealised gain).' },{ text: 'Retained earnings', correct: true, explanation: 'Correct!' },{ text: 'Capital redemption reserve', correct: false, explanation: 'Non-distributable.' }] },
  // --- IAS Standards (8) ---
  { questionText: 'IAS 1 requires financial statements to include:', topic: 'IAS 1 Presentation', difficulty: 'medium', syllabusRef: '2.1',
    aiExplanation: 'IAS 1 requires: Statement of financial position, Statement of profit or loss and other comprehensive income, Statement of changes in equity, Statement of cash flows, and Notes (including accounting policies).',
    options: [{ text: 'Only a P&L and balance sheet', correct: false, explanation: 'More statements required.' },{ text: 'Five components including cash flows and notes', correct: true, explanation: 'Correct!' },{ text: 'Only a trial balance', correct: false, explanation: 'TB is a working document, not a financial statement.' },{ text: 'Tax computation and P&L only', correct: false, explanation: 'Tax computation is not a financial statement.' }] },
  { questionText: 'Under IAS 16, the cost of property, plant and equipment includes:', topic: 'IAS 16 Property Plant & Equipment', difficulty: 'medium', syllabusRef: '2.2',
    aiExplanation: 'IAS 16 cost includes: purchase price (less discounts), import duties, directly attributable costs to bring to working condition (delivery, installation, site preparation, professional fees). Excludes: admin/overhead costs, training, abnormal waste.',
    options: [{ text: 'Purchase price only', correct: false, explanation: 'Must include directly attributable costs.' },{ text: 'Purchase price plus directly attributable costs', correct: true, explanation: 'Correct!' },{ text: 'Any costs incurred in the first year', correct: false, explanation: 'Only costs to bring to working condition.' },{ text: 'Purchase price plus staff training', correct: false, explanation: 'Training costs are excluded.' }] },
  { questionText: 'IAS 38 defines an intangible asset as:', topic: 'IAS 38 Intangible Assets', difficulty: 'medium', syllabusRef: '2.3',
    aiExplanation: 'IAS 38: an identifiable non-monetary asset without physical substance. Must be: identifiable (separable or arising from contractual/legal rights), controlled by the entity, and expected to generate future economic benefits. Examples: patents, trademarks, software, customer lists.',
    options: [{ text: 'Any asset without a physical form', correct: false, explanation: 'Must also be identifiable and controlled.' },{ text: 'An identifiable non-monetary asset without physical substance', correct: true, explanation: 'Correct!' },{ text: 'Goodwill only', correct: false, explanation: 'Goodwill is ONE type of intangible.' },{ text: 'Any investment', correct: false, explanation: 'Investments have different accounting treatment.' }] },
  { questionText: 'Under IAS 16, the revaluation model allows PPE to be carried at:', topic: 'IAS 16 Property Plant & Equipment', difficulty: 'medium', syllabusRef: '2.4',
    aiExplanation: 'Revaluation model: asset carried at fair value less subsequent depreciation and impairment. Revaluations must be regular. Gains go to revaluation reserve (OCI). Losses go to P&L (unless reversing a previous gain). Entire class must be revalued.',
    options: [{ text: 'Historical cost only', correct: false, explanation: 'That is the cost model.' },{ text: 'Fair value less subsequent depreciation', correct: true, explanation: 'Correct!' },{ text: 'Replacement cost', correct: false, explanation: 'Fair value, not replacement cost.' },{ text: 'Scrap value', correct: false, explanation: 'Not scrap value.' }] },
  { questionText: 'Research costs under IAS 38 are:', topic: 'IAS 38 Intangible Assets', difficulty: 'medium', syllabusRef: '2.5',
    aiExplanation: 'IAS 38 requires: Research costs = always expensed (cannot be capitalised). Development costs = capitalised if ALL criteria met (PIRATE: Probable future benefits, Intention to complete, Resources available, Ability to use/sell, Technical feasibility, Expenditure measurable). If any criterion not met, expense immediately.',
    options: [{ text: 'Always capitalised', correct: false, explanation: 'Research costs are ALWAYS expensed.' },{ text: 'Always expensed to P&L', correct: true, explanation: 'Correct!' },{ text: 'Capitalised if criteria are met', correct: false, explanation: 'That rule applies to DEVELOPMENT costs, not research.' },{ text: 'Ignored', correct: false, explanation: 'Must be recognised as an expense.' }] },
  { questionText: 'IAS 2 requires inventory to be valued at:', topic: 'IAS 16 Property Plant & Equipment', difficulty: 'easy', syllabusRef: '2.6',
    aiExplanation: 'IAS 2: lower of cost and net realisable value. Cost includes: purchase price, conversion costs, other costs to bring to current condition. NRV = estimated selling price less costs to complete and sell. LIFO is not permitted.',
    options: [{ text: 'Higher of cost and NRV', correct: false, explanation: 'LOWER, not higher — prudence concept.' },{ text: 'Lower of cost and NRV', correct: true, explanation: 'Correct!' },{ text: 'Cost only', correct: false, explanation: 'Must consider NRV.' },{ text: 'Selling price', correct: false, explanation: 'NRV, not selling price (NRV deducts selling costs).' }] },
  { questionText: 'IAS 10 Events After the Reporting Period: an adjusting event is one that:', topic: 'IAS 1 Presentation', difficulty: 'hard', syllabusRef: '2.7',
    aiExplanation: 'Adjusting events provide evidence of conditions existing at the year end. Financial statements are adjusted. Examples: settlement of a court case, bankruptcy of a customer (debt existed at year end). Non-adjusting events relate to conditions arising AFTER year end (e.g., fire, share price fall).',
    options: [{ text: 'Provides evidence of conditions at the year end', correct: true, explanation: 'Correct! Adjust the financial statements.' },{ text: 'Occurs after the year end regardless of relevance', correct: false, explanation: 'Must relate to year-end conditions.' },{ text: 'Only involves cash transactions', correct: false, explanation: 'Not limited to cash events.' },{ text: 'Is always disclosed in notes', correct: false, explanation: 'Adjusting events modify figures, not just notes.' }] },
  { questionText: 'Under IAS 37, a provision is recognised when:', topic: 'IAS 1 Presentation', difficulty: 'hard', syllabusRef: '2.8',
    aiExplanation: 'IAS 37 provision criteria: (1) present obligation from a past event, (2) probable outflow of economic benefits, (3) reliable estimate of the amount. All three must be met. If not, it is disclosed as a contingent liability (if probable but not reliably estimable) or ignored (if only possible).',
    options: [{ text: 'There is a present obligation, probable outflow, and reliable estimate', correct: true, explanation: 'Correct! All three criteria.' },{ text: 'The business thinks it might need to pay something', correct: false, explanation: 'Too vague — all three criteria must be met.' },{ text: 'The amount is known exactly', correct: false, explanation: 'A reliable ESTIMATE is sufficient.' },{ text: 'The directors decide to make one', correct: false, explanation: 'Must meet IAS 37 criteria, not just a management decision.' }] },
  // --- Statement of Cash Flows (8) ---
  { questionText: 'The statement of cash flows (IAS 7) classifies cash flows into:', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'easy', syllabusRef: '3.1',
    aiExplanation: 'Three categories: Operating activities (day-to-day trading), Investing activities (buying/selling non-current assets), Financing activities (raising/repaying finance — shares, loans, dividends).',
    options: [{ text: 'Operating, investing, and financing', correct: true, explanation: 'Correct!' },{ text: 'Income, expenses, and capital', correct: false, explanation: 'P&L classifications, not cash flow.' },{ text: 'Current, non-current, and equity', correct: false, explanation: 'SOFP classifications.' },{ text: 'Direct, indirect, and net', correct: false, explanation: 'Direct and indirect are methods, not categories.' }] },
  { questionText: 'Using the indirect method, cash from operating activities starts with:', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'easy', syllabusRef: '3.2',
    aiExplanation: 'Indirect method starts with profit before tax, then adjusts for: depreciation (add back — non-cash), profit/loss on disposals, changes in working capital (inventory, receivables, payables), interest and tax paid.',
    options: [{ text: 'Cash balance', correct: false, explanation: 'Cash balance is the final figure.' },{ text: 'Profit before tax', correct: true, explanation: 'Correct!' },{ text: 'Revenue', correct: false, explanation: 'Revenue is not the starting point.' },{ text: 'Net assets', correct: false, explanation: 'SOFP figure, not cash flow starting point.' }] },
  { questionText: 'Depreciation is added back in the cash flow statement because:', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'medium', syllabusRef: '3.3',
    aiExplanation: 'Depreciation was deducted in calculating profit, but it is NOT a cash outflow (no money leaves the business). Therefore, it must be added back to convert profit to cash from operations.',
    options: [{ text: 'It is a cash payment', correct: false, explanation: 'Depreciation is NOT a cash flow.' },{ text: 'It was deducted from profit but is not a cash outflow', correct: true, explanation: 'Correct!' },{ text: 'It increases cash', correct: false, explanation: 'It doesn\'t change cash — it\'s a non-cash adjustment.' },{ text: 'IAS 7 requires it as income', correct: false, explanation: 'It\'s an adjustment, not income.' }] },
  { questionText: 'An increase in trade receivables during the year means:', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'medium', syllabusRef: '3.4',
    aiExplanation: 'Higher receivables = more credit given = less cash collected than revenue recorded. This is a cash outflow relative to profit. Deducted in operating activities.',
    options: [{ text: 'More cash was collected than earned', correct: false, explanation: 'Less cash collected if receivables increased.' },{ text: 'Less cash was collected — deducted in operating activities', correct: true, explanation: 'Correct!' },{ text: 'No effect on cash', correct: false, explanation: 'Working capital changes affect cash.' },{ text: 'Cash increased', correct: false, explanation: 'Cash decreased relative to profit.' }] },
  { questionText: 'Purchase of a new machine for £25,000 appears in which section?', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'easy', syllabusRef: '3.5',
    aiExplanation: 'Buying non-current assets is an investing activity — cash outflow. Selling NCAs is also investing — cash inflow.',
    options: [{ text: 'Operating activities', correct: false, explanation: 'Day-to-day trading, not asset purchases.' },{ text: 'Investing activities', correct: true, explanation: 'Correct!' },{ text: 'Financing activities', correct: false, explanation: 'Financing is about shares and loans.' },{ text: 'Not shown in cash flows', correct: false, explanation: 'It IS a cash flow — investing.' }] },
  { questionText: 'Dividends paid to shareholders appear in which section?', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'easy', syllabusRef: '3.6',
    aiExplanation: 'Under IAS 7, dividends paid can be classified as either operating or financing. Under UK practice and common exam convention, dividends paid are usually classified as financing activities.',
    options: [{ text: 'Operating activities', correct: false, explanation: 'Possible under IAS 7 but not standard UK practice.' },{ text: 'Financing activities', correct: true, explanation: 'Correct! Standard UK classification.' },{ text: 'Investing activities', correct: false, explanation: 'Investing is about non-current assets.' },{ text: 'Not included in cash flows', correct: false, explanation: 'Must be included.' }] },
  { questionText: 'Issue of new shares for cash appears in:', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'easy', syllabusRef: '3.7',
    aiExplanation: 'Issuing shares raises finance — financing activity (cash inflow). Repaying a loan is also financing (cash outflow).',
    options: [{ text: 'Operating activities', correct: false, explanation: 'Not day-to-day trading.' },{ text: 'Investing activities', correct: false, explanation: 'Not about non-current assets.' },{ text: 'Financing activities', correct: true, explanation: 'Correct!' },{ text: 'Statement of changes in equity only', correct: false, explanation: 'Also appears in cash flows.' }] },
  { questionText: 'An increase in trade payables means:', topic: 'Statement of Cash Flows (IAS 7)', difficulty: 'medium', syllabusRef: '3.8',
    aiExplanation: 'Higher payables = more credit taken from suppliers = less cash paid out than expenses recorded. This is a cash benefit relative to profit. ADDED in operating activities.',
    options: [{ text: 'More cash paid to suppliers', correct: false, explanation: 'Less cash paid if payables increased.' },{ text: 'Less cash paid — added back in operating activities', correct: true, explanation: 'Correct!' },{ text: 'No effect on cash', correct: false, explanation: 'Working capital changes affect cash.' },{ text: 'A financing inflow', correct: false, explanation: 'Trade payables are operating, not financing.' }] },
  // --- Ratio Analysis (16) ---
  { questionText: 'Current ratio is calculated as:', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.1',
    aiExplanation: 'Current ratio = Current assets ÷ Current liabilities. Measures short-term liquidity. Ideal is around 1.5:1 to 2:1. Below 1 means the business may struggle to pay short-term debts.',
    options: [{ text: 'Current assets ÷ Current liabilities', correct: true, explanation: 'Correct!' },{ text: 'Current liabilities ÷ Current assets', correct: false, explanation: 'Inverted.' },{ text: 'Total assets ÷ Total liabilities', correct: false, explanation: 'That is a different ratio.' },{ text: 'Non-current assets ÷ Current liabilities', correct: false, explanation: 'Not the current ratio.' }] },
  { questionText: 'Current assets £45,000, current liabilities £30,000. Current ratio?', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.2',
    aiExplanation: '£45,000 ÷ £30,000 = 1.5:1. The business has £1.50 of current assets for every £1 of current liabilities.',
    options: [{ text: '1.5:1', correct: true, explanation: 'Correct!' },{ text: '0.67:1', correct: false, explanation: 'Inverted the ratio.' },{ text: '2:1', correct: false, explanation: 'Incorrect calculation.' },{ text: '15:1', correct: false, explanation: 'Arithmetic error.' }] },
  { questionText: 'Quick ratio (acid test) excludes which current asset?', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.3',
    aiExplanation: 'Quick ratio = (Current assets - Inventory) ÷ Current liabilities. Inventory is excluded because it is the least liquid current asset — it may not be quickly converted to cash. Ideal is around 1:1.',
    options: [{ text: 'Trade receivables', correct: false, explanation: 'Receivables are included.' },{ text: 'Inventory', correct: true, explanation: 'Correct! Least liquid current asset.' },{ text: 'Bank balance', correct: false, explanation: 'Cash/bank is included.' },{ text: 'Prepayments', correct: false, explanation: 'While some exclude prepayments, the key exclusion is inventory.' }] },
  { questionText: 'Gross profit margin is:', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.4',
    aiExplanation: 'Gross profit margin = (Gross profit ÷ Revenue) × 100. Shows the percentage of revenue retained after cost of sales. Higher is better.',
    options: [{ text: '(Gross profit ÷ Revenue) × 100', correct: true, explanation: 'Correct!' },{ text: '(Net profit ÷ Revenue) × 100', correct: false, explanation: 'That is net profit margin.' },{ text: '(Revenue ÷ Gross profit) × 100', correct: false, explanation: 'Inverted.' },{ text: '(Cost of sales ÷ Revenue) × 100', correct: false, explanation: 'That gives the cost ratio, not profit margin.' }] },
  { questionText: 'Revenue £200,000, cost of sales £120,000. Gross profit margin?', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.5',
    aiExplanation: 'GP = £200,000 - £120,000 = £80,000. GP margin = (£80,000 ÷ £200,000) × 100 = 40%.',
    options: [{ text: '40%', correct: true, explanation: 'Correct!' },{ text: '60%', correct: false, explanation: 'That is the cost ratio (COGS÷Revenue).' },{ text: '66.7%', correct: false, explanation: 'Incorrect calculation.' },{ text: '80%', correct: false, explanation: 'Not a percentage of revenue.' }] },
  { questionText: 'Return on capital employed (ROCE) measures:', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.6',
    aiExplanation: 'ROCE = (Operating profit ÷ Capital employed) × 100. Capital employed = Total assets - Current liabilities (or Equity + Non-current liabilities). It measures how efficiently the business uses its capital to generate profit. Higher is better.',
    options: [{ text: 'How efficiently capital generates profit', correct: true, explanation: 'Correct!' },{ text: 'How quickly inventory is sold', correct: false, explanation: 'That is inventory turnover.' },{ text: 'How much cash is available', correct: false, explanation: 'That is a liquidity measure.' },{ text: 'The dividend paid to shareholders', correct: false, explanation: 'Not about dividends.' }] },
  { questionText: 'Trade receivables days = (Trade receivables ÷ Credit sales) × 365. Receivables £20,000, credit sales £146,000. Receivable days?', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.7',
    aiExplanation: '(£20,000 ÷ £146,000) × 365 = 50 days (rounded). This means on average, customers take 50 days to pay.',
    options: [{ text: '50 days', correct: true, explanation: 'Correct!' },{ text: '73 days', correct: false, explanation: 'Incorrect calculation.' },{ text: '7.3 days', correct: false, explanation: 'Too low.' },{ text: '365 days', correct: false, explanation: 'Would mean no one pays all year.' }] },
  { questionText: 'Trade payable days = (Trade payables ÷ Credit purchases) × 365. Payables £15,000, purchases £109,500. Payable days?', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.8',
    aiExplanation: '(£15,000 ÷ £109,500) × 365 = 50 days (rounded). This means on average, the business takes 50 days to pay suppliers.',
    options: [{ text: '50 days', correct: true, explanation: 'Correct!' },{ text: '73 days', correct: false, explanation: 'Incorrect calculation.' },{ text: '7.3 days', correct: false, explanation: 'Too low.' },{ text: '137 days', correct: false, explanation: 'Incorrect calculation.' }] },
  { questionText: 'Inventory turnover days = (Inventory ÷ Cost of sales) × 365. Inventory £10,000, COGS £73,000. Inventory days?', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.9',
    aiExplanation: '(£10,000 ÷ £73,000) × 365 = 50 days. Inventory sits in stock for an average of 50 days before being sold.',
    options: [{ text: '50 days', correct: true, explanation: 'Correct!' },{ text: '7.3 days', correct: false, explanation: 'Divided by 365 instead of multiplied.' },{ text: '73 days', correct: false, explanation: 'Incorrect calculation.' },{ text: '365 days', correct: false, explanation: 'Would mean stock never sells.' }] },
  { questionText: 'Gearing ratio measures:', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.10',
    aiExplanation: 'Gearing = (Non-current liabilities ÷ (Equity + Non-current liabilities)) × 100. Or: Debt ÷ Equity. It measures the proportion of finance from debt vs equity. Higher gearing = more debt = more risk but potential higher returns.',
    options: [{ text: 'Proportion of finance from debt vs equity', correct: true, explanation: 'Correct!' },{ text: 'Profitability', correct: false, explanation: 'Use ROCE or margins for profitability.' },{ text: 'Liquidity', correct: false, explanation: 'Use current/quick ratio for liquidity.' },{ text: 'Efficiency', correct: false, explanation: 'Use asset turnover for efficiency.' }] },
  { questionText: 'A company with high gearing (70%) faces which risk?', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.11',
    aiExplanation: 'High gearing means heavy reliance on debt financing. Risks: interest payments must be met regardless of profit, potential insolvency if unable to service debt, less financial flexibility, vulnerable to interest rate increases.',
    options: [{ text: 'Higher interest costs and potential insolvency if profits fall', correct: true, explanation: 'Correct!' },{ text: 'Lower returns for shareholders', correct: false, explanation: 'High gearing can increase returns IF profits are good.' },{ text: 'Too much cash', correct: false, explanation: 'Debt creates obligations, not excess cash.' },{ text: 'No risk — debt is always beneficial', correct: false, explanation: 'High debt increases financial risk.' }] },
  { questionText: 'Interest cover ratio = Operating profit ÷ Interest expense. Operating profit £60,000, interest £12,000. Interest cover?', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.12',
    aiExplanation: '£60,000 ÷ £12,000 = 5 times. The business can pay its interest 5 times over from operating profit. Higher is safer — below 2 is concerning.',
    options: [{ text: '5 times', correct: true, explanation: 'Correct!' },{ text: '0.2 times', correct: false, explanation: 'Inverted.' },{ text: '72,000 times', correct: false, explanation: 'Added instead of dividing.' },{ text: '48,000 times', correct: false, explanation: 'Subtracted instead of dividing.' }] },
  { questionText: 'Asset turnover = Revenue ÷ Net assets. Revenue £500,000, net assets £200,000. Asset turnover?', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.13',
    aiExplanation: '£500,000 ÷ £200,000 = 2.5 times. Each £1 of net assets generates £2.50 of revenue. Higher asset turnover means more efficient use of assets.',
    options: [{ text: '2.5 times', correct: true, explanation: 'Correct!' },{ text: '0.4 times', correct: false, explanation: 'Inverted.' },{ text: '40%', correct: false, explanation: 'Not expressed as a percentage.' },{ text: '£300,000', correct: false, explanation: 'Subtracted instead of dividing.' }] },
  { questionText: 'Earnings per share (EPS) is calculated as:', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.14',
    aiExplanation: 'EPS = Profit after tax attributable to ordinary shareholders ÷ Number of ordinary shares in issue. It shows the profit earned per share and is a key measure for investors.',
    options: [{ text: 'Profit after tax ÷ Number of ordinary shares', correct: true, explanation: 'Correct!' },{ text: 'Revenue ÷ Number of shares', correct: false, explanation: 'Revenue, not profit.' },{ text: 'Dividends ÷ Number of shares', correct: false, explanation: 'That is dividends per share.' },{ text: 'Share price ÷ Profit', correct: false, explanation: 'That relates to P/E ratio (inverted).' }] },
  { questionText: 'Price/Earnings (P/E) ratio = Market price per share ÷ EPS. Share price £4.50, EPS 30p. P/E ratio?', topic: 'Ratio Analysis', difficulty: 'medium', syllabusRef: '4.15',
    aiExplanation: '£4.50 ÷ £0.30 = 15. A P/E of 15 means investors are willing to pay 15 times the company\'s earnings per share. Higher P/E suggests market expects growth.',
    options: [{ text: '15', correct: true, explanation: 'Correct!' },{ text: '1.5', correct: false, explanation: 'Used £3 or wrong EPS.' },{ text: '0.067', correct: false, explanation: 'Inverted.' },{ text: '150', correct: false, explanation: 'Used pence for one and pounds for other.' }] },
  { questionText: 'Which ratio best measures a company\'s ability to pay its debts as they fall due?', topic: 'Ratio Analysis', difficulty: 'easy', syllabusRef: '4.16',
    aiExplanation: 'The current ratio (and quick ratio) measure short-term liquidity — the ability to pay debts as they fall due. Current ratio = Current assets ÷ Current liabilities.',
    options: [{ text: 'Gross profit margin', correct: false, explanation: 'Measures profitability, not liquidity.' },{ text: 'Current ratio', correct: true, explanation: 'Correct!' },{ text: 'Gearing ratio', correct: false, explanation: 'Measures long-term financial structure.' },{ text: 'Asset turnover', correct: false, explanation: 'Measures efficiency, not liquidity.' }] },
];

async function main() {
  console.log('\n🎓 Seeding L4 FASL...\n');
  await seedModule('FASL', FASL);
  console.log('\n✅ Done!');
}
main().catch(console.error).finally(() => prisma.$disconnect());
