export interface ModuleGuideData {
  title: string;
  titlePt: string;
  description: string;
  descriptionPt: string;
  steps: { label: string; labelPt: string }[];
  whyImportant: string;
  whyImportantPt: string;
}

export const MODULE_GUIDES: Record<string, ModuleGuideData> = {
  dashboard: {
    title: 'Dashboard — Your Financial Overview',
    titlePt: 'Painel — Sua Visão Financeira Geral',
    description: 'The Dashboard is your central hub for understanding your financial health at a glance. It displays key metrics such as total income, expenses, savings rate, and upcoming bills. Use it daily to stay on top of your finances.',
    descriptionPt: 'O Painel é seu centro de controle para entender sua saúde financeira de forma rápida. Ele exibe métricas como renda total, despesas, taxa de economia e contas próximas. Use diariamente para manter o controle.',
    steps: [
      { label: 'Review your monthly income vs expenses summary', labelPt: 'Revise o resumo mensal de receitas vs despesas' },
      { label: 'Check upcoming bills and payment deadlines', labelPt: 'Verifique contas próximas e prazos de pagamento' },
      { label: 'Monitor your savings rate and financial goals', labelPt: 'Acompanhe sua taxa de economia e metas financeiras' },
      { label: 'Spot trends in your spending patterns', labelPt: 'Identifique tendências nos seus padrões de gastos' },
    ],
    whyImportant: 'A clear overview prevents financial surprises. Regular monitoring helps you make informed decisions, avoid overspending, and build wealth over time.',
    whyImportantPt: 'Uma visão clara previne surpresas financeiras. Monitoramento regular ajuda você a tomar decisões informadas, evitar gastos excessivos e construir patrimônio.',
  },
  academy: {
    title: 'Academy — Financial Education Centre',
    titlePt: 'Academia — Centro de Educação Financeira',
    description: 'The Academy provides structured courses and tutorials on personal finance, tax planning, and money management in the UK. Learn at your own pace with practical, actionable content.',
    descriptionPt: 'A Academia oferece cursos e tutoriais sobre finanças pessoais, planejamento tributário e gestão financeira no Reino Unido. Aprenda no seu ritmo com conteúdo prático e aplicável.',
    steps: [
      { label: 'Browse available courses by topic', labelPt: 'Navegue pelos cursos disponíveis por tema' },
      { label: 'Start with beginner modules if you are new to UK finance', labelPt: 'Comece com módulos iniciantes se é novo nas finanças do UK' },
      { label: 'Complete lessons and track your progress', labelPt: 'Complete lições e acompanhe seu progresso' },
      { label: 'Apply what you learn directly in Clarity & Co', labelPt: 'Aplique o que aprendeu diretamente no Clarity & Co' },
    ],
    whyImportant: 'Financial literacy is the foundation of wealth building. Understanding how UK taxes, savings accounts, and pensions work can save you thousands of pounds per year.',
    whyImportantPt: 'Educação financeira é a base da construção de patrimônio. Entender como funcionam impostos, contas de poupança e pensões no UK pode economizar milhares de libras por ano.',
  },
  actions: {
    title: 'Actions — Your Financial To-Do List',
    titlePt: 'Ações — Sua Lista de Tarefas Financeiras',
    description: 'Actions keeps track of all your pending financial tasks — from filing a tax return to calling your utility provider. Never miss a deadline or forget an important financial step.',
    descriptionPt: 'Ações mantém o controle de todas as suas tarefas financeiras pendentes — de declarar impostos a ligar para a fornecedora de serviços. Nunca perca um prazo ou esqueça um passo importante.',
    steps: [
      { label: 'Create actions for upcoming financial tasks', labelPt: 'Crie ações para tarefas financeiras futuras' },
      { label: 'Set due dates and priorities', labelPt: 'Defina datas de vencimento e prioridades' },
      { label: 'Mark actions as complete when done', labelPt: 'Marque ações como concluídas quando finalizar' },
      { label: 'Review regularly to stay organised', labelPt: 'Revise regularmente para manter-se organizado' },
    ],
    whyImportant: 'Missed deadlines cost money — late tax returns attract penalties, missed bill payments damage credit scores. A structured action list keeps you proactive rather than reactive.',
    whyImportantPt: 'Prazos perdidos custam dinheiro — declarações fiscais atrasadas geram multas, pagamentos perdidos prejudicam o score de crédito. Uma lista de ações mantém você proativo.',
  },
  bills: {
    title: 'Bills — Recurring Expense Management',
    titlePt: 'Contas — Gestão de Despesas Recorrentes',
    description: 'Track all your recurring household bills in one place — rent, utilities, subscriptions, insurance. Know exactly what you owe each month and never miss a payment.',
    descriptionPt: 'Controle todas as contas recorrentes da casa em um só lugar — aluguel, serviços, assinaturas, seguros. Saiba exatamente o que você deve a cada mês e nunca perca um pagamento.',
    steps: [
      { label: 'Add all your recurring bills with amounts and due dates', labelPt: 'Adicione todas as contas recorrentes com valores e vencimentos' },
      { label: 'Categorise each bill (utilities, subscriptions, etc.)', labelPt: 'Categorize cada conta (serviços, assinaturas, etc.)' },
      { label: 'Scan bills using AI to auto-extract details', labelPt: 'Escaneie contas usando IA para extrair detalhes automaticamente' },
      { label: 'Review monthly totals to find savings opportunities', labelPt: 'Revise totais mensais para encontrar oportunidades de economia' },
    ],
    whyImportant: 'Household bills are often the largest expense. Tracking them reveals overspending, identifies cheaper alternatives, and ensures nothing falls through the cracks.',
    whyImportantPt: 'Contas domésticas são frequentemente a maior despesa. Rastreá-las revela gastos excessivos, identifica alternativas mais baratas e garante que nada seja esquecido.',
  },
  documents: {
    title: 'Capture & Classify — Smart Document Scanning',
    titlePt: 'Capture & Classify — Digitalização Inteligente de Documentos',
    description: 'Scan receipts, bills, and financial documents using your phone or desktop. Our AI extracts key information automatically and organises everything for you.',
    descriptionPt: 'Escaneie recibos, contas e documentos financeiros usando seu celular ou desktop. Nossa IA extrai informações automaticamente e organiza tudo para você.',
    steps: [
      { label: 'Upload or scan a document using camera or file upload', labelPt: 'Faça upload ou escaneie um documento usando câmera ou arquivo' },
      { label: 'AI automatically extracts merchant, amount, date, and category', labelPt: 'A IA extrai automaticamente fornecedor, valor, data e categoria' },
      { label: 'Review and confirm extracted data', labelPt: 'Revise e confirme os dados extraídos' },
      { label: 'Use QR code for mobile scanning from your phone', labelPt: 'Use QR code para escanear do celular' },
    ],
    whyImportant: 'Paper receipts fade and get lost. Digital records are permanent, searchable, and essential for tax returns and expense claims. Capture everything now, find it instantly later.',
    whyImportantPt: 'Recibos de papel desbotam e se perdem. Registros digitais são permanentes, pesquisáveis e essenciais para declarações fiscais. Capture tudo agora, encontre instantaneamente depois.',
  },
  categories: {
    title: 'Categories — Organise Your Finances',
    titlePt: 'Categorias — Organize Suas Finanças',
    description: 'Categories are the backbone of your financial organisation. Every transaction, bill, and invoice is tagged with a category so you can see exactly where your money goes.',
    descriptionPt: 'Categorias são a base da sua organização financeira. Cada transação, conta e fatura é marcada com uma categoria para que você veja exatamente para onde vai seu dinheiro.',
    steps: [
      { label: 'Review the default categories provided', labelPt: 'Revise as categorias padrão fornecidas' },
      { label: 'Create custom categories that match your lifestyle', labelPt: 'Crie categorias personalizadas que combinem com seu estilo de vida' },
      { label: 'Assign parent categories for hierarchical organisation', labelPt: 'Atribua categorias pai para organização hierárquica' },
      { label: 'Use categories consistently when adding transactions', labelPt: 'Use categorias consistentemente ao adicionar transações' },
    ],
    whyImportant: 'Without proper categorisation, your financial data is just numbers. Categories turn raw data into actionable insights — "I spent £450 on dining out this month" is far more useful than "I spent £450."',
    whyImportantPt: 'Sem categorização adequada, seus dados financeiros são apenas números. Categorias transformam dados brutos em insights — "Gastei £450 em restaurantes este mês" é muito mais útil que "Gastei £450."',
  },
  categorizationRules: {
    title: 'Smart Rules — Automatic Transaction Categorisation',
    titlePt: 'Regras Inteligentes — Categorização Automática de Transações',
    description: 'Smart Rules use a 4-layer AI engine to automatically categorise your transactions. The system learns from your corrections and gets smarter over time.',
    descriptionPt: 'Regras Inteligentes usam um mecanismo de IA de 4 camadas para categorizar automaticamente suas transações. O sistema aprende com suas correções e fica mais inteligente ao longo do tempo.',
    steps: [
      { label: 'Review existing rules for common merchants', labelPt: 'Revise regras existentes para fornecedores comuns' },
      { label: 'Create custom rules for your specific transactions', labelPt: 'Crie regras personalizadas para suas transações específicas' },
      { label: 'Correct mis-categorised transactions to train the AI', labelPt: 'Corrija transações mal categorizadas para treinar a IA' },
      { label: 'Monitor metrics to see categorisation accuracy improve', labelPt: 'Monitore métricas para ver a precisão melhorar' },
    ],
    whyImportant: 'Manual categorisation is tedious and error-prone. Smart Rules automate 90%+ of the work, saving you hours each month while improving accuracy.',
    whyImportantPt: 'Categorização manual é tediosa e propensa a erros. Regras Inteligentes automatizam 90%+ do trabalho, economizando horas todo mês com maior precisão.',
  },
  connections: {
    title: 'Connections — Link Your Financial Accounts',
    titlePt: 'Conexões — Conecte Suas Contas Financeiras',
    description: 'Connect your bank accounts, credit cards, and financial services to automatically import transactions. Open Banking sync keeps everything up to date.',
    descriptionPt: 'Conecte suas contas bancárias, cartões de crédito e serviços financeiros para importar transações automaticamente. A sincronização Open Banking mantém tudo atualizado.',
    steps: [
      { label: 'Connect your bank accounts via Open Banking', labelPt: 'Conecte suas contas bancárias via Open Banking' },
      { label: 'Link credit cards for expense tracking', labelPt: 'Vincule cartões de crédito para rastreamento de despesas' },
      { label: 'Enable automatic sync (up to 3x daily)', labelPt: 'Habilite sincronização automática (até 3x por dia)' },
      { label: 'Review imported transactions for accuracy', labelPt: 'Revise transações importadas para verificar precisão' },
    ],
    whyImportant: 'Manual data entry leads to missed transactions and errors. Automatic bank connections give you a complete, accurate picture of your finances with zero effort.',
    whyImportantPt: 'Entrada manual de dados leva a transações perdidas e erros. Conexões bancárias automáticas dão uma visão completa e precisa das suas finanças sem esforço.',
  },
  email: {
    title: 'Email — Financial Communications Hub',
    titlePt: 'Email — Central de Comunicações Financeiras',
    description: 'Manage your financial emails in one place. Send and receive communications related to your household finances, tax matters, and professional services.',
    descriptionPt: 'Gerencie seus emails financeiros em um só lugar. Envie e receba comunicações relacionadas às finanças domésticas, assuntos fiscais e serviços profissionais.',
    steps: [
      { label: 'Review incoming financial correspondence', labelPt: 'Revise correspondências financeiras recebidas' },
      { label: 'Send inquiries to service providers', labelPt: 'Envie consultas a prestadores de serviços' },
      { label: 'Keep a record of all financial communications', labelPt: 'Mantenha um registro de todas as comunicações financeiras' },
      { label: 'Archive important emails for future reference', labelPt: 'Arquive emails importantes para referência futura' },
    ],
    whyImportant: 'Financial communications contain critical information — confirmation numbers, agreements, and deadlines. Having them organised and accessible prevents costly oversights.',
    whyImportantPt: 'Comunicações financeiras contêm informações críticas — números de confirmação, acordos e prazos. Tê-las organizadas previne erros custosos.',
  },
  englishHub: {
    title: 'English Hub — Language Support for Finances',
    titlePt: 'English Hub — Suporte Linguístico para Finanças',
    description: 'The English Hub helps non-native speakers understand UK financial terminology. Learn essential vocabulary for banking, taxes, and everyday financial tasks in the UK.',
    descriptionPt: 'O English Hub ajuda falantes não nativos a entender a terminologia financeira do Reino Unido. Aprenda vocabulário essencial para bancos, impostos e tarefas financeiras do dia a dia.',
    steps: [
      { label: 'Browse financial vocabulary by topic', labelPt: 'Navegue pelo vocabulário financeiro por tema' },
      { label: 'Learn key phrases for banking and official communications', labelPt: 'Aprenda frases-chave para bancos e comunicações oficiais' },
      { label: 'Practice with real-world UK financial scenarios', labelPt: 'Pratique com cenários financeiros reais do UK' },
      { label: 'Build confidence for financial interactions in English', labelPt: 'Construa confiança para interações financeiras em inglês' },
    ],
    whyImportant: 'Understanding financial English is essential for managing money in the UK. Misunderstanding a term in a contract or bank statement can lead to costly mistakes.',
    whyImportantPt: 'Entender inglês financeiro é essencial para gerenciar dinheiro no UK. Não entender um termo em um contrato ou extrato bancário pode levar a erros custosos.',
  },
  entities: {
    title: 'Entities — Manage Your Financial Identities',
    titlePt: 'Entidades — Gerencie Suas Identidades Financeiras',
    description: 'Entities represent the different financial identities you manage — your personal finances, a business, a property company, or a family member. Keep each set of finances separate and organised.',
    descriptionPt: 'Entidades representam as diferentes identidades financeiras que você gerencia — finanças pessoais, um negócio, uma empresa imobiliária ou um membro da família. Mantenha cada conjunto de finanças separado e organizado.',
    steps: [
      { label: 'Create an entity for each financial identity you manage', labelPt: 'Crie uma entidade para cada identidade financeira que você gerencia' },
      { label: 'Set the entity type (personal, business, etc.)', labelPt: 'Defina o tipo de entidade (pessoal, negócio, etc.)' },
      { label: 'Switch between entities using the header selector', labelPt: 'Alterne entre entidades usando o seletor no cabeçalho' },
      { label: 'All transactions, bills, and reports are filtered by entity', labelPt: 'Todas as transações, contas e relatórios são filtrados por entidade' },
    ],
    whyImportant: 'Mixing personal and business finances is a common mistake that creates tax complications. Entities keep everything cleanly separated for accurate reporting.',
    whyImportantPt: 'Misturar finanças pessoais e de negócios é um erro comum que cria complicações fiscais. Entidades mantêm tudo separado para relatórios precisos.',
  },
  files: {
    title: 'Files — Your Financial Document Library',
    titlePt: 'Arquivos — Sua Biblioteca de Documentos Financeiros',
    description: 'Store and organise all your financial documents securely — contracts, tax returns, payslips, insurance policies. Everything in one searchable, cloud-backed location.',
    descriptionPt: 'Armazene e organize todos os seus documentos financeiros com segurança — contratos, declarações fiscais, holerites, apólices de seguro. Tudo em um local pesquisável na nuvem.',
    steps: [
      { label: 'Upload important financial documents', labelPt: 'Faça upload de documentos financeiros importantes' },
      { label: 'Organise files into folders by type or year', labelPt: 'Organize arquivos em pastas por tipo ou ano' },
      { label: 'Use search to find documents instantly', labelPt: 'Use a busca para encontrar documentos instantaneamente' },
      { label: 'Keep digital copies of all paper documents', labelPt: 'Mantenha cópias digitais de todos os documentos em papel' },
    ],
    whyImportant: 'HMRC can request records going back 6 years. Having all documents organised and accessible means you are always audit-ready and can resolve disputes quickly.',
    whyImportantPt: 'A HMRC pode solicitar registros de até 6 anos atrás. Ter todos os documentos organizados significa que você está sempre pronto para auditorias.',
  },
  household: {
    title: 'Household — Family Finance Management',
    titlePt: 'Família — Gestão Financeira Familiar',
    description: 'Manage your entire household\'s finances together. Track shared expenses, assign budgets to family members, and coordinate financial goals as a family unit.',
    descriptionPt: 'Gerencie as finanças de toda a família juntos. Rastreie despesas compartilhadas, atribua orçamentos a membros da família e coordene metas financeiras como uma unidade familiar.',
    steps: [
      { label: 'Add household members and their roles', labelPt: 'Adicione membros da família e seus papéis' },
      { label: 'Set shared budgets and spending limits', labelPt: 'Defina orçamentos compartilhados e limites de gastos' },
      { label: 'Track who paid for what', labelPt: 'Rastreie quem pagou o quê' },
      { label: 'Review household spending reports together', labelPt: 'Revise relatórios de gastos domésticos juntos' },
    ],
    whyImportant: 'Household finances affect everyone in the family. Transparent management prevents conflicts, ensures fair contributions, and helps achieve shared goals like buying a home.',
    whyImportantPt: 'Finanças domésticas afetam todos na família. Gestão transparente previne conflitos, garante contribuições justas e ajuda a alcançar metas compartilhadas.',
  },
  intelligence: {
    title: 'Intelligence — AI-Powered Financial Insights',
    titlePt: 'Inteligência — Insights Financeiros com IA',
    description: 'Intelligence analyses all your financial data using AI to surface insights you might miss. Get personalised recommendations, spending alerts, and predictive analysis.',
    descriptionPt: 'A Inteligência analisa todos os seus dados financeiros usando IA para revelar insights que você poderia perder. Receba recomendações personalizadas, alertas de gastos e análise preditiva.',
    steps: [
      { label: 'Review AI-generated insights and recommendations', labelPt: 'Revise insights e recomendações gerados pela IA' },
      { label: 'Check spending anomalies and alerts', labelPt: 'Verifique anomalias de gastos e alertas' },
      { label: 'Explore predictive cash flow analysis', labelPt: 'Explore análise preditiva de fluxo de caixa' },
      { label: 'Act on recommendations to improve your finances', labelPt: 'Aja com base nas recomendações para melhorar suas finanças' },
    ],
    whyImportant: 'AI can spot patterns humans miss — unusual charges, saving opportunities, and upcoming cash flow problems. Early detection prevents financial problems from growing.',
    whyImportantPt: 'IA pode identificar padrões que humanos perdem — cobranças incomuns, oportunidades de economia e problemas de fluxo de caixa. Detecção precoce previne problemas.',
  },
  invoices: {
    title: 'Invoices — Income & Billing Management',
    titlePt: 'Faturas — Gestão de Renda e Faturamento',
    description: 'Upload bank statements or manually add invoices to track all your income and expenses. AI automatically categorises transactions and identifies patterns.',
    descriptionPt: 'Faça upload de extratos bancários ou adicione faturas manualmente para rastrear toda sua renda e despesas. A IA categoriza transações automaticamente e identifica padrões.',
    steps: [
      { label: 'Upload a bank statement (CSV, PDF, or image)', labelPt: 'Faça upload de um extrato bancário (CSV, PDF ou imagem)' },
      { label: 'AI extracts and categorises each transaction', labelPt: 'A IA extrai e categoriza cada transação' },
      { label: 'Review flagged transactions that need attention', labelPt: 'Revise transações sinalizadas que precisam de atenção' },
      { label: 'Confirm or correct categories to improve future accuracy', labelPt: 'Confirme ou corrija categorias para melhorar a precisão futura' },
    ],
    whyImportant: 'Tracking income and expenses is the foundation of financial management. Without it, you cannot budget, save, or plan. Consistent tracking reveals your true financial position.',
    whyImportantPt: 'Rastrear receitas e despesas é a base da gestão financeira. Sem isso, você não pode orçar, economizar ou planejar. Rastreamento consistente revela sua verdadeira posição financeira.',
  },
  learn: {
    title: 'Learn — UK Finance Knowledge Base',
    titlePt: 'Aprender — Base de Conhecimento Financeiro do UK',
    description: 'Access a comprehensive library of guides and articles about UK financial topics — from National Insurance to ISAs, pensions, and property taxes.',
    descriptionPt: 'Acesse uma biblioteca abrangente de guias e artigos sobre temas financeiros do UK — de National Insurance a ISAs, pensões e impostos sobre propriedades.',
    steps: [
      { label: 'Browse topics relevant to your situation', labelPt: 'Navegue por temas relevantes à sua situação' },
      { label: 'Read step-by-step guides for specific tasks', labelPt: 'Leia guias passo a passo para tarefas específicas' },
      { label: 'Bookmark important articles for future reference', labelPt: 'Favorite artigos importantes para referência futura' },
      { label: 'Apply knowledge to improve your financial decisions', labelPt: 'Aplique o conhecimento para melhorar suas decisões financeiras' },
    ],
    whyImportant: 'UK finance has unique rules and systems. Understanding them — ISAs, tax codes, National Insurance — is essential for maximising your income and minimising tax liability.',
    whyImportantPt: 'Finanças no UK têm regras e sistemas únicos. Entendê-los — ISAs, códigos fiscais, National Insurance — é essencial para maximizar sua renda e minimizar impostos.',
  },
  lifeEvents: {
    title: 'Life Events — Financial Impact Planning',
    titlePt: 'Eventos de Vida — Planejamento de Impacto Financeiro',
    description: 'Major life events have major financial impacts. Track events like marriage, having a baby, buying a home, or retirement to understand and prepare for their financial effects.',
    descriptionPt: 'Grandes eventos de vida têm grandes impactos financeiros. Rastreie eventos como casamento, ter um bebê, comprar uma casa ou aposentadoria para entender e se preparar para seus efeitos financeiros.',
    steps: [
      { label: 'Record upcoming or recent life events', labelPt: 'Registre eventos de vida futuros ou recentes' },
      { label: 'See the estimated financial impact of each event', labelPt: 'Veja o impacto financeiro estimado de cada evento' },
      { label: 'Get checklists of financial actions to take', labelPt: 'Obtenha checklists de ações financeiras a tomar' },
      { label: 'Plan ahead to minimise financial stress', labelPt: 'Planeje com antecedência para minimizar estresse financeiro' },
    ],
    whyImportant: 'Being financially prepared for life events reduces stress and prevents debt. A baby costs an average of £12,000 in the first year — planning ahead makes it manageable.',
    whyImportantPt: 'Estar financeiramente preparado para eventos de vida reduz estresse e previne dívidas. Um bebê custa em média £12.000 no primeiro ano — planejar com antecedência torna isso administrável.',
  },
  productCalculator: {
    title: 'Product Calculator — Financial Product Comparison',
    titlePt: 'Calculadora de Produtos — Comparação de Produtos Financeiros',
    description: 'Compare financial products like mortgages, loans, savings accounts, and credit cards. Calculate real costs including interest, fees, and tax implications.',
    descriptionPt: 'Compare produtos financeiros como hipotecas, empréstimos, contas de poupança e cartões de crédito. Calcule custos reais incluindo juros, taxas e implicações fiscais.',
    steps: [
      { label: 'Select the type of financial product to compare', labelPt: 'Selecione o tipo de produto financeiro para comparar' },
      { label: 'Enter the details (amount, term, rates)', labelPt: 'Insira os detalhes (valor, prazo, taxas)' },
      { label: 'Compare total costs across different options', labelPt: 'Compare custos totais entre diferentes opções' },
      { label: 'Make informed decisions based on real numbers', labelPt: 'Tome decisões informadas com base em números reais' },
    ],
    whyImportant: 'The wrong mortgage can cost you tens of thousands extra over its term. Proper comparison ensures you get the best deal and avoid hidden fees.',
    whyImportantPt: 'A hipoteca errada pode custar dezenas de milhares a mais ao longo do prazo. Comparação adequada garante o melhor negócio e evita taxas ocultas.',
  },
  projections: {
    title: 'Projections — Financial Forecasting',
    titlePt: 'Projeções — Previsão Financeira',
    description: 'Project your future financial position based on current income, expenses, and trends. See where you will be in 3, 6, or 12 months and adjust your plans accordingly.',
    descriptionPt: 'Projete sua posição financeira futura com base na renda, despesas e tendências atuais. Veja onde você estará em 3, 6 ou 12 meses e ajuste seus planos.',
    steps: [
      { label: 'Review your projected cash flow', labelPt: 'Revise seu fluxo de caixa projetado' },
      { label: 'Add known future income and expenses', labelPt: 'Adicione receitas e despesas futuras conhecidas' },
      { label: 'Explore "what if" scenarios', labelPt: 'Explore cenários "e se"' },
      { label: 'Adjust spending to meet your financial targets', labelPt: 'Ajuste gastos para alcançar suas metas financeiras' },
    ],
    whyImportant: 'Looking ahead prevents nasty surprises. Knowing you will have a cash shortfall in March gives you time to prepare, rather than scrambling when it happens.',
    whyImportantPt: 'Olhar adiante previne surpresas desagradáveis. Saber que terá um déficit de caixa em março dá tempo para se preparar.',
  },
  properties: {
    title: 'Properties — Real Estate Portfolio',
    titlePt: 'Propriedades — Portfólio Imobiliário',
    description: 'Track your property portfolio — residential, rental, or commercial. Monitor values, rental income, mortgage payments, and maintenance costs all in one place.',
    descriptionPt: 'Rastreie seu portfólio de propriedades — residencial, aluguel ou comercial. Monitore valores, renda de aluguel, pagamentos de hipoteca e custos de manutenção em um só lugar.',
    steps: [
      { label: 'Add your properties with purchase details', labelPt: 'Adicione suas propriedades com detalhes de compra' },
      { label: 'Track mortgage payments and remaining balance', labelPt: 'Rastreie pagamentos de hipoteca e saldo restante' },
      { label: 'Record rental income and tenant information', labelPt: 'Registre renda de aluguel e informações dos inquilinos' },
      { label: 'Monitor property values and equity growth', labelPt: 'Monitore valores de propriedades e crescimento de patrimônio' },
    ],
    whyImportant: 'Property is often your largest asset and liability. Tracking all costs — mortgage, insurance, maintenance, taxes — reveals true return on investment and aids tax reporting.',
    whyImportantPt: 'Propriedade é frequentemente seu maior ativo e passivo. Rastrear todos os custos revela o retorno real do investimento e auxilia na declaração de impostos.',
  },
  providers: {
    title: 'Providers — Service Provider Directory',
    titlePt: 'Fornecedores — Diretório de Prestadores de Serviços',
    description: 'Keep a directory of all your financial service providers — banks, insurance companies, utility providers, accountants. Quick access to contact details and account references.',
    descriptionPt: 'Mantenha um diretório de todos os seus prestadores de serviços financeiros — bancos, seguradoras, fornecedoras de serviços, contadores. Acesso rápido a detalhes de contato e referências.',
    steps: [
      { label: 'Add each service provider with contact details', labelPt: 'Adicione cada prestador de serviço com detalhes de contato' },
      { label: 'Include account/reference numbers', labelPt: 'Inclua números de conta/referência' },
      { label: 'Note contract renewal dates', labelPt: 'Anote datas de renovação de contrato' },
      { label: 'Compare providers when contracts are up for renewal', labelPt: 'Compare fornecedores quando contratos estiverem para renovação' },
    ],
    whyImportant: 'When you need to contact a provider urgently — a fraud alert, a billing error — having all details in one place saves crucial time.',
    whyImportantPt: 'Quando você precisa contatar um fornecedor urgentemente — alerta de fraude, erro de cobrança — ter todos os detalhes em um lugar economiza tempo crucial.',
  },
  relocation: {
    title: 'Relocation — Moving & Settling Guide',
    titlePt: 'Relocação — Guia de Mudança e Estabelecimento',
    description: 'Planning a move to or within the UK? The Relocation module guides you through all the financial steps — opening a bank account, registering for council tax, setting up utilities.',
    descriptionPt: 'Planejando uma mudança para ou dentro do UK? O módulo de Relocação guia você por todos os passos financeiros — abrir conta bancária, registrar council tax, configurar serviços.',
    steps: [
      { label: 'Follow the step-by-step relocation checklist', labelPt: 'Siga o checklist passo a passo de relocação' },
      { label: 'Set up essential financial accounts', labelPt: 'Configure contas financeiras essenciais' },
      { label: 'Register for taxes and council services', labelPt: 'Registre-se para impostos e serviços do council' },
      { label: 'Compare local service providers', labelPt: 'Compare prestadores de serviços locais' },
    ],
    whyImportant: 'Relocating involves dozens of financial tasks. Missing one — like registering for council tax — can result in penalties. A structured guide ensures nothing is forgotten.',
    whyImportantPt: 'Relocar envolve dezenas de tarefas financeiras. Esquecer uma — como registrar-se para council tax — pode resultar em multas. Um guia estruturado garante que nada seja esquecido.',
  },
  reports: {
    title: 'Reports — Financial Reports & Analytics',
    titlePt: 'Relatórios — Relatórios Financeiros e Análises',
    description: 'Generate comprehensive financial reports — income statements, expense breakdowns, tax summaries, and trend analysis. Export to PDF for your accountant or HMRC.',
    descriptionPt: 'Gere relatórios financeiros abrangentes — demonstrações de renda, análises de despesas, resumos fiscais e análise de tendências. Exporte em PDF para seu contador ou HMRC.',
    steps: [
      { label: 'Select the report type and date range', labelPt: 'Selecione o tipo de relatório e período' },
      { label: 'Filter by entity, category, or account', labelPt: 'Filtre por entidade, categoria ou conta' },
      { label: 'Review charts and detailed breakdowns', labelPt: 'Revise gráficos e análises detalhadas' },
      { label: 'Export reports for your records or accountant', labelPt: 'Exporte relatórios para seus registros ou contador' },
    ],
    whyImportant: 'Reports transform raw financial data into clear, actionable summaries. They are essential for tax returns, loan applications, and understanding your true financial position.',
    whyImportantPt: 'Relatórios transformam dados financeiros brutos em resumos claros e acionáveis. São essenciais para declarações fiscais, pedidos de empréstimo e entender sua posição financeira.',
  },
  services: {
    title: 'Services — UK Service Directory',
    titlePt: 'Serviços — Diretório de Serviços do UK',
    description: 'Access a curated directory of UK financial and household services — from broadband comparison to energy switching, insurance, and professional services.',
    descriptionPt: 'Acesse um diretório curado de serviços financeiros e domésticos do UK — de comparação de banda larga a mudança de energia, seguros e serviços profissionais.',
    steps: [
      { label: 'Browse services by category', labelPt: 'Navegue por serviços por categoria' },
      { label: 'Compare offers from different providers', labelPt: 'Compare ofertas de diferentes fornecedores' },
      { label: 'Access exclusive deals through Clarity & Co', labelPt: 'Acesse ofertas exclusivas pelo Clarity & Co' },
      { label: 'Track services you have subscribed to', labelPt: 'Rastreie serviços que você assinou' },
    ],
    whyImportant: 'UK households can save hundreds of pounds per year by switching providers. Having all options in one place makes comparison easy and saves money.',
    whyImportantPt: 'Famílias no UK podem economizar centenas de libras por ano trocando de fornecedor. Ter todas as opções em um lugar facilita a comparação e economiza dinheiro.',
  },
  statements: {
    title: 'Statements — Bank Statement Management',
    titlePt: 'Extratos — Gestão de Extratos Bancários',
    description: 'Upload and manage your bank statements. View transaction history, reconcile with your records, and identify discrepancies. Supports CSV, PDF, and image formats.',
    descriptionPt: 'Faça upload e gerencie seus extratos bancários. Visualize histórico de transações, reconcilie com seus registros e identifique discrepâncias. Suporta CSV, PDF e imagens.',
    steps: [
      { label: 'Upload bank statements from your bank\'s website', labelPt: 'Faça upload de extratos bancários do site do seu banco' },
      { label: 'AI parses and categorises all transactions', labelPt: 'A IA analisa e categoriza todas as transações' },
      { label: 'Review and reconcile against your records', labelPt: 'Revise e reconcilie com seus registros' },
      { label: 'Flag unusual or unexpected transactions', labelPt: 'Sinalize transações incomuns ou inesperadas' },
    ],
    whyImportant: 'Regular statement review catches errors, fraud, and forgotten subscriptions. It is the most effective way to maintain accurate financial records.',
    whyImportantPt: 'Revisão regular de extratos detecta erros, fraudes e assinaturas esquecidas. É a forma mais eficaz de manter registros financeiros precisos.',
  },
  taxTimeline: {
    title: 'Tax Timeline — UK Tax Calendar & Deadlines',
    titlePt: 'Calendário Fiscal — Calendário e Prazos Fiscais do UK',
    description: 'Never miss a tax deadline. The Tax Timeline shows all important UK tax dates — Self Assessment, Corporation Tax, VAT returns, PAYE, and more — personalised to your situation.',
    descriptionPt: 'Nunca perca um prazo fiscal. O Calendário Fiscal mostra todas as datas fiscais importantes do UK — Self Assessment, Corporation Tax, VAT, PAYE e mais — personalizado para sua situação.',
    steps: [
      { label: 'Review upcoming tax deadlines', labelPt: 'Revise prazos fiscais próximos' },
      { label: 'Set reminders for important dates', labelPt: 'Configure lembretes para datas importantes' },
      { label: 'Prepare documents before deadlines', labelPt: 'Prepare documentos antes dos prazos' },
      { label: 'Track what has been filed and what is pending', labelPt: 'Rastreie o que foi declarado e o que está pendente' },
    ],
    whyImportant: 'Late tax filing penalties start at £100 and escalate quickly. The Self Assessment deadline of 31 January catches many people out. A timeline keeps you ahead.',
    whyImportantPt: 'Multas por atraso em declarações fiscais começam em £100 e escalam rapidamente. O prazo de Self Assessment de 31 de janeiro pega muitos de surpresa.',
  },
  transfers: {
    title: 'Transfers — Money Movement Tracking',
    titlePt: 'Transferências — Rastreamento de Movimentações',
    description: 'Track money transfers between your accounts, to other people, or international remittances. Keep a clear record of every movement of funds.',
    descriptionPt: 'Rastreie transferências de dinheiro entre suas contas, para outras pessoas ou remessas internacionais. Mantenha um registro claro de cada movimentação de fundos.',
    steps: [
      { label: 'Record transfers between your own accounts', labelPt: 'Registre transferências entre suas próprias contas' },
      { label: 'Track payments to other people or businesses', labelPt: 'Rastreie pagamentos a outras pessoas ou empresas' },
      { label: 'Log international transfers with exchange rates', labelPt: 'Registre transferências internacionais com taxas de câmbio' },
      { label: 'Reconcile transfers with bank statements', labelPt: 'Reconcilie transferências com extratos bancários' },
    ],
    whyImportant: 'Untracked transfers create accounting gaps and confusion. Knowing exactly where money went is essential for accurate records and tax reporting.',
    whyImportantPt: 'Transferências não rastreadas criam lacunas contábeis e confusão. Saber exatamente para onde foi o dinheiro é essencial para registros precisos e declaração de impostos.',
  },
  vault: {
    title: 'Vault — Secure Credential Storage',
    titlePt: 'Cofre — Armazenamento Seguro de Credenciais',
    description: 'Store sensitive financial credentials securely — API keys, account numbers, passwords, PINs, and security codes. Encrypted and accessible only to you.',
    descriptionPt: 'Armazene credenciais financeiras sensíveis com segurança — chaves de API, números de conta, senhas, PINs e códigos de segurança. Criptografado e acessível apenas para você.',
    steps: [
      { label: 'Add credentials with a descriptive name', labelPt: 'Adicione credenciais com um nome descritivo' },
      { label: 'Categorise by type (bank, API, insurance, etc.)', labelPt: 'Categorize por tipo (banco, API, seguro, etc.)' },
      { label: 'Access when needed — click to reveal', labelPt: 'Acesse quando necessário — clique para revelar' },
      { label: 'Update credentials when they change', labelPt: 'Atualize credenciais quando mudarem' },
    ],
    whyImportant: 'Keeping credentials in unsecured places (sticky notes, text files) is a security risk. The Vault provides military-grade encryption for your most sensitive information.',
    whyImportantPt: 'Manter credenciais em locais inseguros (post-its, arquivos de texto) é um risco de segurança. O Cofre oferece criptografia de nível militar para suas informações mais sensíveis.',
  },
  insurance: {
    title: 'Insurance — Policy Management & Protection',
    titlePt: 'Seguros — Gestão de Apólices e Proteção',
    description: 'Manage all your insurance policies in one place — life, car, motorcycle, home, health, and travel. Track premiums, renewal dates, coverage amounts, and never miss a renewal.',
    descriptionPt: 'Gerencie todas as suas apólices de seguro em um só lugar — vida, carro, moto, casa, saúde e viagem. Rastreie prêmios, datas de renovação, valores de cobertura e nunca perca uma renovação.',
    steps: [
      { label: 'Add your insurance policies with provider and coverage details', labelPt: 'Adicione suas apólices com detalhes do provedor e cobertura' },
      { label: 'Set renewal dates to get timely reminders', labelPt: 'Defina datas de renovação para receber lembretes oportunos' },
      { label: 'Track monthly and annual premium costs', labelPt: 'Rastreie custos de prêmios mensais e anuais' },
      { label: 'Compare policies when renewals are due to find better deals', labelPt: 'Compare apólices quando as renovações vencerem para encontrar melhores ofertas' },
    ],
    whyImportant: 'Insurance is essential protection but also a significant expense. Tracking all policies prevents gaps in coverage, catches auto-renewals at inflated prices, and ensures you are adequately protected.',
    whyImportantPt: 'Seguro é proteção essencial mas também uma despesa significativa. Rastrear todas as apólices previne lacunas na cobertura, detecta renovações automáticas com preços inflados e garante proteção adequada.',
  },
  correspondence: {
    title: 'Correspondence — Official Mail Registry',
    titlePt: 'Correspondência — Registro de Correio Oficial',
    description: 'Track and archive all official correspondence — HMRC notices, Companies House letters, council tax documents, bank letters, insurance renewals, and legal notices. Never lose track of deadlines or important references.',
    descriptionPt: 'Rastreie e arquive toda correspondência oficial — avisos do HMRC, cartas da Companies House, documentos de council tax, cartas bancárias, renovações de seguros e avisos legais. Nunca perca prazos ou referências importantes.',
    steps: [
      { label: 'Scan a letter via Capture & Classify — it auto-creates a Correspondence entry', labelPt: 'Escaneie uma carta via Capture & Classify — cria automaticamente uma entrada de Correspondência' },
      { label: 'Set the status workflow: Received → Under Review → Action Taken → Resolved', labelPt: 'Defina o workflow de status: Recebido → Em Análise → Ação Tomada → Resolvido' },
      { label: 'Track deadlines and get reminders before they expire', labelPt: 'Rastreie prazos e receba lembretes antes de vencerem' },
      { label: 'Reply to correspondence and build a chain of communication', labelPt: 'Responda correspondências e construa uma cadeia de comunicação' },
    ],
    whyImportant: 'Official correspondence often contains critical deadlines, payment references, and legal obligations. Missing an HMRC filing deadline can result in automatic penalties. A proper registry ensures nothing falls through the cracks.',
    whyImportantPt: 'Correspondência oficial frequentemente contém prazos críticos, referências de pagamento e obrigações legais. Perder um prazo do HMRC pode resultar em multas automáticas. Um registro adequado garante que nada seja esquecido.',
  },
  settings: {
    title: 'Settings — Personalise Your Experience',
    titlePt: 'Configurações — Personalize Sua Experiência',
    description: 'Configure Clarity & Co to work exactly the way you need. Set your language, currency display, notification preferences, categorisation mode, and account details.',
    descriptionPt: 'Configure o Clarity & Co para funcionar exatamente do jeito que você precisa. Defina idioma, exibição de moeda, preferências de notificação, modo de categorização e detalhes da conta.',
    steps: [
      { label: 'Set your preferred language and region', labelPt: 'Defina seu idioma e região preferidos' },
      { label: 'Upload your profile logo or avatar', labelPt: 'Faça upload do seu logo ou avatar de perfil' },
      { label: 'Choose your categorisation mode (Conservative/Smart/Autonomous)', labelPt: 'Escolha seu modo de categorização (Conservador/Inteligente/Autônomo)' },
      { label: 'Manage notification and email preferences', labelPt: 'Gerencie preferências de notificação e email' },
    ],
    whyImportant: 'Customised settings make the system work for you, not against you. The right categorisation mode alone can save hours of manual work each month.',
    whyImportantPt: 'Configurações personalizadas fazem o sistema trabalhar para você. O modo de categorização certo pode economizar horas de trabalho manual por mês.',
  },
};
